# Generated by Django 4.2.7 on 2025-10-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LayananContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("phone", "Telepon"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("address", "Alamat"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Kontak",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Nilai")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Deskripsi"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Kontak Utama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
            ],
            options={
                "verbose_name": "Kontak Layanan",
                "verbose_name_plural": "Kontak Layanan",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LayananFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pertanyaan")),
                ("answer", models.TextField(verbose_name="Jawaban")),
                ("category", models.CharField(max_length=100, verbose_name="Kategori")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
            ],
            options={
                "verbose_name": "FAQ Layanan",
                "verbose_name_plural": "FAQ Layanan",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LayananFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telepon"),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("suggestion", "Saran"),
                            ("complaint", "Keluhan"),
                            ("praise", "Pujian"),
                            ("other", "Lainnya"),
                        ],
                        default="suggestion",
                        max_length=20,
                        verbose_name="Jenis Feedback",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subjek")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anonim"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Sudah Diproses"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
            ],
            options={
                "verbose_name": "Feedback Layanan",
                "verbose_name_plural": "Feedback Layanan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LayananService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nama Layanan")),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icon"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
            ],
            options={
                "verbose_name": "Layanan",
                "verbose_name_plural": "Layanan",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
