# Generated by Django 4.2.7 on 2025-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layanancontact",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Kontak Layanan",
                "verbose_name_plural": "Kontak Layanan",
            },
        ),
        migrations.RemoveField(
            model_name="layanancontact",
            name="contact_type",
        ),
        migrations.RemoveField(
            model_name="layanancontact",
            name="description",
        ),
        migrations.RemoveField(
            model_name="layanancontact",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="layanancontact",
            name="order",
        ),
        migrations.RemoveField(
            model_name="layanancontact",
            name="value",
        ),
        migrations.RemoveField(
            model_name="layananfeedback",
            name="feedback_type",
        ),
        migrations.RemoveField(
            model_name="layananfeedback",
            name="is_anonymous",
        ),
        migrations.RemoveField(
            model_name="layananfeedback",
            name="is_processed",
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="department",
            field=models.CharField(
                default="Umum", max_length=100, verbose_name="Departemen"
            ),
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="email",
            field=models.EmailField(
                default="kontak@desa.id", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="name",
            field=models.CharField(
                default="Kontak", max_length=100, verbose_name="Nama"
            ),
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Catatan"),
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="phone",
            field=models.CharField(
                default="0000000000", max_length=20, verbose_name="Telepon"
            ),
        ),
        migrations.AddField(
            model_name="layanancontact",
            name="position",
            field=models.CharField(
                default="Staff", max_length=100, verbose_name="Jabatan"
            ),
        ),
        migrations.AddField(
            model_name="layananfeedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("complaint", "Keluhan"),
                    ("suggestion", "Saran"),
                    ("question", "Pertanyaan"),
                    ("praise", "Pujian"),
                ],
                default="suggestion",
                max_length=20,
                verbose_name="Kategori",
            ),
        ),
        migrations.AddField(
            model_name="layananfeedback",
            name="replied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dibalas Pada"
            ),
        ),
        migrations.AddField(
            model_name="layananfeedback",
            name="reply",
            field=models.TextField(blank=True, verbose_name="Balasan"),
        ),
        migrations.AddField(
            model_name="layananfeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Menunggu"),
                    ("read", "Sudah Dibaca"),
                    ("replied", "Sudah Dibalas"),
                    ("closed", "Ditutup"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="layananservice",
            name="category",
            field=models.CharField(
                choices=[
                    ("documents", "Dokumen"),
                    ("health", "Kesehatan"),
                    ("business", "Bisnis"),
                    ("tourism", "Pariwisata"),
                    ("other", "Lainnya"),
                ],
                default="other",
                max_length=20,
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="layananfaq",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "Umum"),
                    ("documents", "Dokumen"),
                    ("services", "Layanan"),
                    ("technical", "Teknis"),
                ],
                default="general",
                max_length=20,
                verbose_name="Kategori",
            ),
        ),
    ]
