# Generated by Django 4.2.7 on 2025-10-03 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentsettings_villageinfo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layanan", "0002_alter_layanancontact_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayananDocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nama Lengkap"),
                ),
                ("nik", models.CharField(max_length=16, verbose_name="NIK")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Nomor Telepon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(verbose_name="Alamat Lengkap")),
                (
                    "purpose",
                    models.CharField(max_length=200, verbose_name="Tujuan Penggunaan"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Keterangan Tambahan"),
                ),
                (
                    "ktp_file",
                    models.FileField(
                        blank=True,
                        upload_to="layanan/ktp/",
                        verbose_name="Fotokopi KTP",
                    ),
                ),
                (
                    "kk_file",
                    models.FileField(
                        blank=True, upload_to="layanan/kk/", verbose_name="Fotokopi KK"
                    ),
                ),
                (
                    "additional_file",
                    models.FileField(
                        blank=True,
                        upload_to="layanan/additional/",
                        verbose_name="Dokumen Tambahan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Alasan Penolakan"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Diproses Pada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui Pada"),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layanan_requests",
                        to="documents.documenttype",
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diproses Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permintaan Dokumen Layanan",
                "verbose_name_plural": "Permintaan Dokumen Layanan",
                "ordering": ["-created_at"],
            },
        ),
    ]
