# Generated by Django 4.2.16 on 2025-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layanan", "0003_layanandocumentrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layanandocumentrequest",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("surat_keterangan", "Surat Keterangan"),
                    ("surat_pengantar", "Surat Pengantar"),
                    ("surat_izin", "Surat Izin"),
                    ("surat_rekomendasi", "Surat Rekomendasi"),
                    ("surat_kepemilikan", "Surat Kepemilikan"),
                    ("surat_lainnya", "Surat Lainnya"),
                ],
                default="surat_keterangan",
                max_length=50,
                verbose_name="Jenis Dokumen",
            ),
        ),
    ]
