# Generated by Django 5.2.6 on 2025-09-12 23:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TourismCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Kategori"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Slug URL",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon FontAwesome"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Warna"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/categories/",
                        verbose_name="Gambar Kategori",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/categories/videos/",
                        verbose_name="Video Kategori",
                    ),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, null=True, verbose_name="Link YouTube"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/categories/hero/",
                        verbose_name="Gambar Hero",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/categories/hero/videos/",
                        verbose_name="Video Hero",
                    ),
                ),
                (
                    "hero_youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Hero"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Wisata",
                "verbose_name_plural": "Kategori Wisata",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TourismDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Wisata Desa Pulosarok",
                        max_length=200,
                        verbose_name="Judul Dashboard",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Sub Judul"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Jelajahi keindahan alam, kekayaan budaya, dan kelezatan kuliner yang menanti Anda di setiap sudut desa kami.",
                        verbose_name="Deskripsi",
                    ),
                ),
                (
                    "hero_background",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/hero/",
                        verbose_name="Background Hero",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/hero/videos/",
                        verbose_name="Video Hero",
                    ),
                ),
                (
                    "hero_youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Hero"),
                ),
                (
                    "featured_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/sections/",
                        verbose_name="Background Destinasi Unggulan",
                    ),
                ),
                (
                    "categories_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/sections/",
                        verbose_name="Background Kategori",
                    ),
                ),
                (
                    "events_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/sections/",
                        verbose_name="Background Event",
                    ),
                ),
                (
                    "packages_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/dashboard/sections/",
                        verbose_name="Background Paket",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Warna Primer"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10B981", max_length=7, verbose_name="Warna Sekunder"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#8B5CF6", max_length=7, verbose_name="Warna Aksen"
                    ),
                ),
                (
                    "show_statistics",
                    models.BooleanField(
                        default=True, verbose_name="Tampilkan Statistik"
                    ),
                ),
                (
                    "show_featured_locations",
                    models.BooleanField(
                        default=True, verbose_name="Tampilkan Destinasi Unggulan"
                    ),
                ),
                (
                    "show_categories",
                    models.BooleanField(
                        default=True, verbose_name="Tampilkan Kategori"
                    ),
                ),
                (
                    "show_events",
                    models.BooleanField(default=True, verbose_name="Tampilkan Event"),
                ),
                (
                    "show_packages",
                    models.BooleanField(default=True, verbose_name="Tampilkan Paket"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Keywords"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Wisata",
                "verbose_name_plural": "Dashboard Wisata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismPageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Wisata Desa",
                        max_length=200,
                        verbose_name="Judul Halaman",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Jelajahi keindahan alam, kekayaan budaya, dan kelezatan kuliner yang menanti Anda di setiap sudut desa kami.",
                        verbose_name="Deskripsi Halaman",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/page_headers/",
                        verbose_name="Gambar Background",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Header Halaman Wisata",
                "verbose_name_plural": "Header Halaman Wisata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Wisata"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug URL",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("natural", "Wisata Alam"),
                            ("cultural", "Wisata Budaya"),
                            ("historical", "Wisata Sejarah"),
                            ("religious", "Wisata Religi"),
                            ("culinary", "Wisata Kuliner"),
                            ("adventure", "Wisata Petualangan"),
                            ("education", "Wisata Edukasi"),
                            ("other", "Lainnya"),
                        ],
                        default="natural",
                        max_length=20,
                        verbose_name="Jenis Wisata",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(max_length=500, verbose_name="Deskripsi Singkat"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Deskripsi Lengkap"),
                ),
                ("address", models.TextField(verbose_name="Alamat Lengkap")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Jam Buka"
                    ),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Biaya Masuk",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "facilities",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="List of facilities in JSON format",
                        verbose_name="Fasilitas",
                    ),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="List of activities in JSON format",
                        verbose_name="Aktivitas yang Tersedia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Dipublikasi"),
                            ("archived", "Diarsipkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Wisata Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/locations/",
                        verbose_name="Gambar Utama",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/locations/hero/",
                        verbose_name="Gambar Hero",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/locations/hero/videos/",
                        verbose_name="Video Hero",
                    ),
                ),
                (
                    "hero_youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Hero"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta Keywords"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Publikasi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourism.tourismcategory",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tourism_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tourism_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupdate Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokasi Wisata",
                "verbose_name_plural": "Lokasi Wisata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Gambar"),
                            ("video", "Video"),
                            ("360", "Foto 360°"),
                        ],
                        default="image",
                        max_length=10,
                        verbose_name="Jenis Media",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul")),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/gallery/",
                        verbose_name="Gambar",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="URL Video")),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/videos/",
                        verbose_name="File Video",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Text"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Caption"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Gambar Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeri Wisata",
                "verbose_name_plural": "Galeri Wisata",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Pertanyaan")),
                ("answer", models.TextField(verbose_name="Jawaban")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kategori"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Wisata",
                "verbose_name_plural": "FAQ Wisata",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="TourismEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul Event")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Slug URL",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("festival", "Festival"),
                            ("exhibition", "Pameran"),
                            ("workshop", "Workshop"),
                            ("competition", "Kompetisi"),
                            ("ceremony", "Upacara"),
                            ("other", "Lainnya"),
                        ],
                        default="festival",
                        max_length=20,
                        verbose_name="Jenis Event",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Event")),
                ("start_date", models.DateTimeField(verbose_name="Tanggal Mulai")),
                ("end_date", models.DateTimeField(verbose_name="Tanggal Selesai")),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Penyelenggara"
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="Informasi Kontak"),
                ),
                (
                    "registration_required",
                    models.BooleanField(
                        default=False, verbose_name="Pendaftaran Diperlukan"
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="URL Pendaftaran"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/events/",
                        verbose_name="Gambar Event",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/events/hero/",
                        verbose_name="Gambar Hero",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/events/hero/videos/",
                        verbose_name="Video Hero",
                    ),
                ),
                (
                    "hero_youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Hero"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Event Unggulan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Wisata",
                "verbose_name_plural": "Event Wisata",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="TourismPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul Paket")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Slug URL",
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("day_trip", "Perjalanan Sehari"),
                            ("weekend", "Paket Weekend"),
                            ("week_long", "Paket Seminggu"),
                            ("custom", "Paket Kustom"),
                        ],
                        default="day_trip",
                        max_length=20,
                        verbose_name="Jenis Paket",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Paket")),
                ("duration", models.CharField(max_length=100, verbose_name="Durasi")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Harga"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IDR", max_length=3, verbose_name="Mata Uang"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Nomor WhatsApp",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/packages/",
                        verbose_name="Gambar Paket",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/packages/videos/",
                        verbose_name="Video Paket",
                    ),
                ),
                (
                    "youtube_link",
                    models.URLField(blank=True, null=True, verbose_name="Link YouTube"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tourism/packages/hero/",
                        verbose_name="Gambar Hero",
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tourism/packages/hero/videos/",
                        verbose_name="Video Hero",
                    ),
                ),
                (
                    "hero_youtube",
                    models.URLField(blank=True, null=True, verbose_name="YouTube Hero"),
                ),
                (
                    "includes",
                    models.TextField(
                        default="[]",
                        help_text="Included items in JSON format",
                        verbose_name="Yang Termasuk",
                    ),
                ),
                (
                    "excludes",
                    models.TextField(
                        default="[]",
                        help_text="Excluded items in JSON format",
                        verbose_name="Yang Tidak Termasuk",
                    ),
                ),
                (
                    "itinerary",
                    models.TextField(
                        default="[]",
                        help_text="Itinerary in JSON format",
                        verbose_name="Itinerary",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maksimal Peserta"
                    ),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Minimal Peserta"
                    ),
                ),
                (
                    "booking_deadline",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Deadline Booking (hari)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Paket Unggulan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paket Wisata",
                "verbose_name_plural": "Paket Wisata",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="TourismPackageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="tourism/packages/gallery/", verbose_name="Gambar"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Judul Gambar",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deskripsi Gambar"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="tourism.tourismpackage",
                        verbose_name="Paket Wisata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeri Paket Wisata",
                "verbose_name_plural": "Galeri Paket Wisata",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TourismReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Review"),
                ),
                ("comment", models.TextField(verbose_name="Komentar")),
                (
                    "visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Kunjungan"
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("personal", "Pribadi"),
                            ("family", "Keluarga"),
                            ("group", "Grup"),
                            ("business", "Bisnis"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Jenis Kunjungan",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Disetujui"),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="Ditandai"),
                ),
                (
                    "flagged_reason",
                    models.TextField(blank=True, verbose_name="Alasan Ditandai"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Wisata",
                "verbose_name_plural": "Review Wisata",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "cleanliness",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Kebersihan",
                    ),
                ),
                (
                    "accessibility",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Aksesibilitas",
                    ),
                ),
                (
                    "facilities",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Fasilitas",
                    ),
                ),
                (
                    "service",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Pelayanan",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nilai",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tourism_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="tourism.tourismlocation",
                        verbose_name="Lokasi Wisata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating Wisata",
                "verbose_name_plural": "Rating Wisata",
                "unique_together": {("tourism_location", "user")},
            },
        ),
    ]
