# Generated by Django 4.2.7 on 2025-09-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tourism", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourismevent",
            name="registration_url",
        ),
        migrations.AddField(
            model_name="tourismcategory",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Kategori Unggulan"),
        ),
        migrations.AddField(
            model_name="tourismcategory",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta Description"
            ),
        ),
        migrations.AddField(
            model_name="tourismcategory",
            name="meta_keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Meta Keywords"
            ),
        ),
        migrations.AddField(
            model_name="tourismcategory",
            name="meta_title",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Meta Title"
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Kontak Person"
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tourism_events_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Waktu Selesai"),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="max_participants",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Maksimal Peserta"
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Nomor Telepon"
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deadline Pendaftaran"
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="registration_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Biaya Pendaftaran",
            ),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="registration_link",
            field=models.URLField(blank=True, verbose_name="Link Pendaftaran"),
        ),
        migrations.AddField(
            model_name="tourismevent",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Waktu Mulai"),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="helpful_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Jumlah Membantu"
            ),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tourism/faqs/",
                verbose_name="Gambar FAQ",
            ),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="FAQ Unggulan"),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="priority",
            field=models.PositiveIntegerField(
                default=3,
                help_text="1 = Sangat Penting, 5 = Tidak Penting",
                verbose_name="Prioritas",
            ),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Pisahkan dengan koma",
                max_length=255,
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tourism/faqs/videos/",
                verbose_name="Video FAQ",
            ),
        ),
        migrations.AddField(
            model_name="tourismfaq",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Jumlah Dilihat"),
        ),
    ]
