# Generated by Django 4.2.7 on 2025-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0002_remove_tourismevent_registration_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourismSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "featured_locations_limit",
                    models.PositiveIntegerField(
                        default=6, verbose_name="Limit Destinasi Unggulan"
                    ),
                ),
                (
                    "categories_limit",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Limit Kategori"
                    ),
                ),
                (
                    "upcoming_events_limit",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Limit Event Mendatang"
                    ),
                ),
                (
                    "featured_packages_limit",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Limit Paket Unggulan"
                    ),
                ),
                (
                    "locations_per_page",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Lokasi per Halaman"
                    ),
                ),
                (
                    "packages_per_page",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Paket per Halaman"
                    ),
                ),
                (
                    "events_per_page",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Event per Halaman"
                    ),
                ),
                (
                    "admin_items_per_page",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Item Admin per Halaman"
                    ),
                ),
                (
                    "reviews_per_page",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Review per Halaman"
                    ),
                ),
                (
                    "related_locations_limit",
                    models.PositiveIntegerField(
                        default=4, verbose_name="Limit Lokasi Terkait"
                    ),
                ),
                (
                    "related_packages_limit",
                    models.PositiveIntegerField(
                        default=6, verbose_name="Limit Paket Terkait"
                    ),
                ),
                (
                    "price_ranges",
                    models.JSONField(
                        default=list,
                        help_text="Format: [{'label': '0-100K', 'min': 0, 'max': 100000}, ...]",
                        verbose_name="Rentang Harga",
                    ),
                ),
                (
                    "duration_filters",
                    models.JSONField(
                        default=list,
                        help_text="Format: [{'label': '1 Hari', 'value': '1 hari'}, ...]",
                        verbose_name="Filter Durasi",
                    ),
                ),
                (
                    "time_filters",
                    models.JSONField(
                        default=list,
                        help_text="Format: [{'label': 'Akan Datang', 'value': 'upcoming'}, ...]",
                        verbose_name="Filter Waktu",
                    ),
                ),
                (
                    "sort_options",
                    models.JSONField(
                        default=list,
                        help_text="Format: [{'label': 'Nama A-Z', 'value': 'name'}, ...]",
                        verbose_name="Opsi Sorting",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor WhatsApp"
                    ),
                ),
                (
                    "whatsapp_message_template",
                    models.TextField(
                        default="Halo, saya tertarik dengan {item_name}",
                        verbose_name="Template Pesan WhatsApp",
                    ),
                ),
                (
                    "enable_real_statistics",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Statistik Real"
                    ),
                ),
                (
                    "cache_statistics_duration",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Durasi Cache Statistik (detik)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pengaturan Wisata",
                "verbose_name_plural": "Pengaturan Wisata",
                "ordering": ["-created_at"],
            },
        ),
    ]
