# Generated by Django 5.2.6 on 2025-09-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Struktur Organisasi", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Informasi lengkap mengenai struktur organisasi dan perangkat desa",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="page_headers/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Header Halaman Organisasi",
                "verbose_name_plural": "Header Halaman Organisasi",
            },
        ),
        migrations.CreateModel(
            name="KarangTaruna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomor_anggota", models.CharField(max_length=50, unique=True)),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("ketua_umum", "Ketua Umum"),
                            ("wakil_ketua", "Wakil Ketua"),
                            ("sekretaris_umum", "Sekretaris Umum"),
                            ("wakil_sekretaris", "Wakil Sekretaris"),
                            ("bendahara_umum", "Bendahara Umum"),
                            ("wakil_bendahara", "Wakil Bendahara"),
                            (
                                "koordinator_bidang_1",
                                "Koordinator Bidang Pendidikan dan Pelatihan",
                            ),
                            (
                                "koordinator_bidang_2",
                                "Koordinator Bidang Olahraga dan Seni",
                            ),
                            (
                                "koordinator_bidang_3",
                                "Koordinator Bidang Kewirausahaan",
                            ),
                            (
                                "koordinator_bidang_4",
                                "Koordinator Bidang Lingkungan Hidup",
                            ),
                            (
                                "koordinator_bidang_5",
                                "Koordinator Bidang Keagamaan dan Sosial",
                            ),
                            ("anggota_aktif", "Anggota Aktif"),
                            ("anggota_biasa", "Anggota Biasa"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tanggal_bergabung", models.DateField()),
                ("tanggal_keluar", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("non_aktif", "Non Aktif"),
                            ("alumni", "Alumni"),
                            ("calon_anggota", "Calon Anggota"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "bidang_keahlian",
                    models.TextField(
                        blank=True, help_text="Bidang keahlian atau minat"
                    ),
                ),
                ("pengalaman_organisasi", models.TextField(blank=True)),
                ("prestasi_individu", models.TextField(blank=True)),
                (
                    "kontribusi",
                    models.TextField(
                        blank=True, help_text="Kontribusi terhadap organisasi"
                    ),
                ),
                (
                    "foto_profil",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization/karang_taruna/"
                    ),
                ),
                ("kontak_whatsapp", models.CharField(blank=True, max_length=20)),
                ("email_pribadi", models.EmailField(blank=True, max_length=254)),
                ("alamat_lengkap", models.TextField(blank=True)),
                ("pendidikan_terakhir", models.CharField(blank=True, max_length=100)),
                ("pekerjaan", models.CharField(blank=True, max_length=100)),
                (
                    "is_pengurus_inti",
                    models.BooleanField(
                        default=False, help_text="Apakah termasuk pengurus inti"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anggota Karang Taruna",
                "verbose_name_plural": "Data Karang Taruna",
                "ordering": ["jabatan", "penduduk__name"],
                "indexes": [
                    models.Index(
                        fields=["jabatan"], name="organizatio_jabatan_8afa62_idx"
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_ea6c3b_idx"
                    ),
                    models.Index(
                        fields=["nomor_anggota"], name="organizatio_nomor_a_635b6c_idx"
                    ),
                    models.Index(
                        fields=["is_pengurus_inti"],
                        name="organizatio_is_peng_58c404_idx",
                    ),
                    models.Index(
                        fields=["jabatan", "status"],
                        name="organizatio_jabatan_2ca9aa_idx",
                    ),
                    models.Index(
                        fields=["status", "is_pengurus_inti"],
                        name="organizatio_status_365524_idx",
                    ),
                    models.Index(
                        fields=["status", "tanggal_bergabung"],
                        name="organizatio_status_37a934_idx",
                    ),
                ],
                "unique_together": {("penduduk", "jabatan")},
            },
        ),
        migrations.CreateModel(
            name="Kepemudaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_organisasi", models.CharField(max_length=200)),
                (
                    "jenis_organisasi",
                    models.CharField(
                        choices=[
                            ("karang_taruna", "Karang Taruna"),
                            ("remaja_masjid", "Remaja Masjid"),
                            ("pramuka", "Pramuka"),
                            ("olahraga", "Organisasi Olahraga"),
                            ("seni_budaya", "Seni dan Budaya"),
                            ("kewirausahaan", "Kewirausahaan Muda"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tanggal_terbentuk", models.DateField()),
                ("jumlah_anggota_aktif", models.PositiveIntegerField(default=0)),
                (
                    "rentang_usia",
                    models.CharField(
                        blank=True, help_text="Contoh: 15-30 tahun", max_length=50
                    ),
                ),
                ("kegiatan_rutin", models.TextField(blank=True)),
                ("prestasi", models.TextField(blank=True)),
                ("alamat_sekretariat", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("non_aktif", "Non Aktif"),
                            ("alumni", "Alumni"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("kontak_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "foto_kegiatan",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization/kepemudaan/"
                    ),
                ),
                ("deskripsi", models.TextField(blank=True)),
                (
                    "media_sosial",
                    models.CharField(
                        blank=True,
                        help_text="Media sosial organisasi (Instagram/Facebook)",
                        max_length=200,
                    ),
                ),
                (
                    "visi_misi",
                    models.TextField(blank=True, help_text="Visi dan misi organisasi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bendahara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bendahara_kepemudaan",
                        to="references.penduduk",
                    ),
                ),
                (
                    "ketua",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ketua_kepemudaan",
                        to="references.penduduk",
                    ),
                ),
                (
                    "sekretaris",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sekretaris_kepemudaan",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisasi Kepemudaan",
                "verbose_name_plural": "Data Kepemudaan",
                "ordering": ["nama_organisasi"],
                "indexes": [
                    models.Index(
                        fields=["nama_organisasi"],
                        name="organizatio_nama_or_f8d9e6_idx",
                    ),
                    models.Index(
                        fields=["jenis_organisasi"],
                        name="organizatio_jenis_o_41e79f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_ac6d66_idx"
                    ),
                    models.Index(
                        fields=["jenis_organisasi", "status"],
                        name="organizatio_jenis_o_d4c58c_idx",
                    ),
                    models.Index(
                        fields=["status", "tanggal_terbentuk"],
                        name="organizatio_status_ce3aed_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LembagaAdat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lembaga", models.CharField(max_length=200)),
                (
                    "jenis_lembaga",
                    models.CharField(
                        choices=[
                            ("adat_istiadat", "Lembaga Adat Istiadat"),
                            ("keagamaan", "Lembaga Keagamaan"),
                            ("budaya", "Lembaga Budaya"),
                            ("tradisi", "Lembaga Tradisi"),
                            ("ritual", "Lembaga Ritual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tanggal_terbentuk", models.DateField()),
                ("alamat_sekretariat", models.TextField(blank=True)),
                ("deskripsi", models.TextField(blank=True)),
                (
                    "kegiatan_rutin",
                    models.TextField(
                        blank=True, help_text="Daftar kegiatan rutin yang dilakukan"
                    ),
                ),
                ("jumlah_anggota", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("non_aktif", "Non Aktif"),
                            ("dalam_pembinaan", "Dalam Pembinaan"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("kontak_phone", models.CharField(blank=True, max_length=20)),
                (
                    "foto_kegiatan",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization/lembaga_adat/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bendahara",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bendahara_lembaga_adat",
                        to="references.penduduk",
                    ),
                ),
                (
                    "ketua",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ketua_lembaga_adat",
                        to="references.penduduk",
                    ),
                ),
                (
                    "sekretaris",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sekretaris_lembaga_adat",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lembaga Adat",
                "verbose_name_plural": "Data Lembaga Adat",
                "ordering": ["nama_lembaga"],
                "indexes": [
                    models.Index(
                        fields=["nama_lembaga"], name="organizatio_nama_le_f6766a_idx"
                    ),
                    models.Index(
                        fields=["jenis_lembaga"], name="organizatio_jenis_l_aa4945_idx"
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_7cce18_idx"
                    ),
                    models.Index(
                        fields=["jenis_lembaga", "status"],
                        name="organizatio_jenis_l_488c4b_idx",
                    ),
                    models.Index(
                        fields=["status", "tanggal_terbentuk"],
                        name="organizatio_status_5e66c1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PenggerakPKK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("ketua_tim_penggerak", "Ketua Tim Penggerak PKK"),
                            ("wakil_ketua", "Wakil Ketua"),
                            ("sekretaris", "Sekretaris"),
                            ("bendahara", "Bendahara"),
                            (
                                "pokja_1",
                                "Pokja I (Penghayatan dan Pengamalan Pancasila)",
                            ),
                            ("pokja_2", "Pokja II (Gotong Royong)"),
                            ("pokja_3", "Pokja III (Pangan, Sandang, Papan)"),
                            ("pokja_4", "Pokja IV (Pendidikan dan Keterampilan)"),
                            ("anggota", "Anggota"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nomor_anggota", models.CharField(blank=True, max_length=50)),
                ("tanggal_bergabung", models.DateField()),
                ("tanggal_keluar", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("non_aktif", "Non Aktif"),
                            ("cuti", "Cuti"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "keahlian",
                    models.TextField(blank=True, help_text="Keahlian yang dimiliki"),
                ),
                ("pengalaman_organisasi", models.TextField(blank=True)),
                ("prestasi", models.TextField(blank=True)),
                (
                    "foto_profil",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization/pkk/"
                    ),
                ),
                ("kontak_whatsapp", models.CharField(blank=True, max_length=20)),
                ("alamat_lengkap", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("deskripsi_tugas", models.TextField(blank=True)),
                ("sk_pengangkatan", models.CharField(blank=True, max_length=100)),
                ("tanggal_mulai_tugas", models.DateField(blank=True, null=True)),
                ("tanggal_selesai_tugas", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penggerak PKK",
                "verbose_name_plural": "Data Penggerak PKK",
                "ordering": ["jabatan", "penduduk__name"],
                "indexes": [
                    models.Index(
                        fields=["jabatan"], name="organizatio_jabatan_2a42f6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_dbb5fb_idx"
                    ),
                    models.Index(
                        fields=["nomor_anggota"], name="organizatio_nomor_a_c02f6d_idx"
                    ),
                    models.Index(
                        fields=["jabatan", "status"],
                        name="organizatio_jabatan_4435e4_idx",
                    ),
                    models.Index(
                        fields=["status", "tanggal_bergabung"],
                        name="organizatio_status_5d90dc_idx",
                    ),
                ],
                "unique_together": {("penduduk", "jabatan")},
            },
        ),
        migrations.CreateModel(
            name="PerangkatDesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("kepala_desa", "Kepala Desa"),
                            ("sekretaris_desa", "Sekretaris Desa"),
                            ("kaur_pemerintahan", "Kaur Pemerintahan"),
                            ("kaur_pembangunan", "Kaur Pembangunan"),
                            ("kaur_kesra", "Kaur Kesejahteraan Rakyat"),
                            ("kaur_keuangan", "Kaur Keuangan"),
                            ("kaur_umum", "Kaur Umum"),
                            ("kasi_pemerintahan", "Kasi Pemerintahan"),
                            ("kasi_pembangunan", "Kasi Pembangunan"),
                            ("kasi_kesra", "Kasi Kesejahteraan Rakyat"),
                            ("kepala_dusun", "Kepala Dusun"),
                            ("staf", "Staf"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nip", models.CharField(blank=True, max_length=50, null=True)),
                ("sk_pengangkatan", models.CharField(blank=True, max_length=100)),
                ("tanggal_mulai_tugas", models.DateField()),
                ("tanggal_selesai_tugas", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("non_aktif", "Non Aktif"),
                            ("pensiun", "Pensiun"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "gaji_pokok",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tunjangan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "foto_profil",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization/perangkat/"
                    ),
                ),
                ("deskripsi_tugas", models.TextField(blank=True)),
                ("kontak_whatsapp", models.CharField(blank=True, max_length=20)),
                ("email_dinas", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perangkat Desa",
                "verbose_name_plural": "Data Perangkat Desa",
                "ordering": ["jabatan", "penduduk__name"],
                "indexes": [
                    models.Index(
                        fields=["jabatan"], name="organizatio_jabatan_e62492_idx"
                    ),
                    models.Index(
                        fields=["status"], name="organizatio_status_7630ec_idx"
                    ),
                    models.Index(fields=["nip"], name="organizatio_nip_634908_idx"),
                    models.Index(
                        fields=["jabatan", "status"],
                        name="organizatio_jabatan_672508_idx",
                    ),
                    models.Index(
                        fields=["status", "tanggal_mulai_tugas"],
                        name="organizatio_status_dac3e4_idx",
                    ),
                ],
                "unique_together": {("penduduk", "jabatan")},
            },
        ),
    ]
