# Generated by Django 4.2.7 on 2025-09-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerangkatDesa",
        ),
    ]
