# Generated by Django 4.2.16 on 2025-10-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0007_alter_pelajar_tahun_masuk"),
        ("organization", "0003_penduduk_alter_karangtaruna_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="karangtaruna",
            options={
                "ordering": ["jabatan", "penduduk__name"],
                "verbose_name": "Anggota Karang Taruna",
                "verbose_name_plural": "Data Karang Taruna",
            },
        ),
        migrations.AlterModelOptions(
            name="penggerakpkk",
            options={
                "ordering": ["jabatan", "penduduk__name"],
                "verbose_name": "Penggerak PKK",
                "verbose_name_plural": "Data Penggerak PKK",
            },
        ),
        migrations.AlterField(
            model_name="karangtaruna",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="references.penduduk"
            ),
        ),
        migrations.AlterField(
            model_name="kepemudaan",
            name="bendahara",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bendahara_kepemudaan",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="kepemudaan",
            name="ketua",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ketua_kepemudaan",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="kepemudaan",
            name="sekretaris",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sekretaris_kepemudaan",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="lembagaadat",
            name="bendahara",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bendahara_lembaga_adat",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="lembagaadat",
            name="ketua",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ketua_lembaga_adat",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="lembagaadat",
            name="sekretaris",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sekretaris_lembaga_adat",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="penggerakpkk",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="references.penduduk"
            ),
        ),
        migrations.DeleteModel(
            name="Penduduk",
        ),
    ]
