# Generated by Django 4.2.7 on 2025-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstag",
            name="color",
            field=models.CharField(
                default="#6c757d", max_length=7, verbose_name="Warna"
            ),
        ),
        migrations.AddField(
            model_name="newstag",
            name="description",
            field=models.TextField(blank=True, verbose_name="Deskripsi"),
        ),
    ]
