# Generated by Django 4.2.7 on 2025-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newstag_color_newstag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscategory",
            name="icon",
            field=models.CharField(
                blank=True, help_text="FontAwesome icon class", max_length=50
            ),
        ),
    ]
