# Generated by Django 4.2.7 on 2025-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("data_manager", "Data Manager"),
                    ("beneficiary_manager", "Manager Penerima Bantuan"),
                    ("business_manager", "Manager Usaha"),
                    ("complaint_manager", "Manager Keluhan"),
                    ("document_manager", "Manager Dokumen"),
                    ("tourism_manager", "Manager Wisata"),
                    ("posyandu_manager", "Manager Posyandu"),
                    ("news_manager", "Manager Berita"),
                    ("village_staff", "Staff Desa"),
                    ("moderator", "Moderator"),
                    ("viewer", "Viewer"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="MenuPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("references", "Data Referensi"),
                            ("beneficiaries", "Penerima Bantuan"),
                            ("business", "Usaha"),
                            ("complaints", "Keluhan"),
                            ("documents", "Dokumen"),
                            ("tourism", "Wisata"),
                            ("posyandu", "Posyandu"),
                            ("news", "Berita"),
                            ("village_profile", "Profil Desa"),
                            ("reports", "Laporan"),
                            ("settings", "Pengaturan"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Lihat"),
                            ("add", "Tambah"),
                            ("change", "Ubah"),
                            ("delete", "Hapus"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Menu Permission",
                "verbose_name_plural": "Menu Permissions",
                "unique_together": {("module", "action")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="menu_permissions",
            field=models.ManyToManyField(blank=True, to="core.menupermission"),
        ),
    ]
