# Generated by Django 4.2.7 on 2025-09-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_menupermission_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Laki-laki"), ("F", "Perempuan")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Nomor telepon", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Foto profil pengguna",
                null=True,
                upload_to="user_photos/",
            ),
        ),
    ]
