# Generated by Django 4.2.7 on 2025-09-19 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_gender_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Alamat IP saat login"),
                ),
                ("user_agent", models.TextField(help_text="User agent browser")),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Nama browser", max_length=50, null=True
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, help_text="Sistem operasi", max_length=50, null=True
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        help_text="Jenis perangkat",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Lokasi berdasarkan IP",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, help_text="Waktu login"),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, help_text="Waktu logout", null=True
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(
                        default=True, help_text="Apakah login berhasil"
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Alasan gagal login",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Login",
                "verbose_name_plural": "Riwayat Login",
                "ordering": ["-login_time"],
            },
        ),
    ]
