# Generated by Django 4.2.7 on 2025-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_loginhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("data_manager", "Data Manager"),
                    ("beneficiary_manager", "Manager Penerima Bantuan"),
                    ("business_manager", "Manager Usaha"),
                    ("complaint_manager", "Manager Keluhan"),
                    ("document_manager", "Manager Dokumen"),
                    ("tourism_manager", "Manager Wisata"),
                    ("posyandu_manager", "Manager Posyandu"),
                    ("news_manager", "Manager Berita"),
                    ("village_profile_manager", "Manager Profil Desa"),
                    ("organization_manager", "Manager Organisasi"),
                    ("karang_taruna_manager", "Manager Karang Taruna"),
                    ("kepemudaan_manager", "Manager Kepemudaan"),
                    ("pkk_manager", "Manager PKK"),
                    ("lembaga_adat_manager", "Manager Lembaga Adat"),
                    ("perangkat_desa_manager", "Manager Perangkat Desa"),
                    ("village_staff", "Staff Desa"),
                    ("moderator", "Moderator"),
                    ("viewer", "Viewer"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
