# Generated by Django 4.2.7 on 2025-09-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admindocumentation",
            name="created_by",
        ),
        migrations.AlterUniqueTogether(
            name="apiendpoint",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="apiendpoint",
            name="module",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="backuplog",
            name="started_by",
        ),
        migrations.DeleteModel(
            name="DashboardWidget",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
        migrations.DeleteModel(
            name="SystemSettings",
        ),
        migrations.DeleteModel(
            name="WebsiteGeneralSettings",
        ),
        migrations.DeleteModel(
            name="WebsiteSEOSettings",
        ),
        migrations.DeleteModel(
            name="WebsiteSystemSettings",
        ),
        migrations.DeleteModel(
            name="AdminDocumentation",
        ),
        migrations.DeleteModel(
            name="APIEndpoint",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="BackupLog",
        ),
        migrations.DeleteModel(
            name="ModuleSettings",
        ),
    ]
