# Generated by Django 4.2.7 on 2025-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_clean_website_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="hero_button_text",
            field=models.CharField(
                default="Jelajahi",
                help_text="Teks tombol di hero section",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="hero_button_url",
            field=models.CharField(
                default="#about", help_text="URL tombol di hero section", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="hero_description",
            field=models.TextField(
                blank=True, help_text="Deskripsi singkat di hero section", null=True
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="hero_subtitle",
            field=models.CharField(
                default="Desa Pulosarok, Kecamatan Cina, Kabupaten Bone",
                help_text="Subtitle di hero section",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="hero_title",
            field=models.CharField(
                default="Selamat Datang",
                help_text="Judul utama di hero section",
                max_length=200,
            ),
        ),
    ]
