# Generated by Django 4.2.7 on 2025-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_websitesettings_hero_button_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("profile", "Profil Desa"),
                            ("population", "Data Penduduk"),
                            ("events", "Kegiatan"),
                            ("news", "Berita"),
                            ("tourism", "Wisata"),
                            ("umkm", "UMKM"),
                            ("organization", "Organisasi"),
                            ("correspondence", "Surat Menyurat"),
                            ("gallery", "Galeri"),
                            ("complaints", "Keluhan"),
                            ("bantuna", "Bantuna"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Gambar hero untuk halaman ini (ukuran kecil, persegi panjang)",
                        upload_to="hero_images/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["page"],
            },
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="hero_button_text",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="hero_button_url",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="hero_description",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="site_description",
        ),
    ]
