# Generated by Django 4.2.7 on 2025-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_herosection_remove_websitesettings_background_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="image",
        ),
        migrations.AddField(
            model_name="herosection",
            name="background_color",
            field=models.CharField(
                default="#3B82F6", help_text="Warna background (hex code)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar background hero section",
                null=True,
                upload_to="hero_sections/backgrounds/",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar hero kecil (persegi panjang)",
                null=True,
                upload_to="hero_sections/images/",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="layout_style",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("centered", "Centered"),
                    ("left", "Left Aligned"),
                    ("right", "Right Aligned"),
                ],
                default="default",
                help_text="Style layout hero section",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle hero section", max_length=300, null=True
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="text_color",
            field=models.CharField(
                default="#FFFFFF", help_text="Warna text (hex code)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="title",
            field=models.CharField(
                blank=True, help_text="Judul hero section", max_length=200, null=True
            ),
        ),
    ]
