# Generated by Django 4.2.7 on 2025-09-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_herosection_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nama gambar hero", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Deskripsi gambar", null=True
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("background", "Background Image"),
                            ("hero", "Hero Image"),
                            ("banner", "Banner Image"),
                            ("overlay", "Overlay Image"),
                        ],
                        default="background",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Gambar hero utama", upload_to="hero_images/%Y/%m/%d/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail gambar (otomatis dibuat)",
                        null=True,
                        upload_to="hero_images/thumbnails/%Y/%m/%d/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text untuk accessibility",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption gambar",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "used_in_pages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Halaman yang menggunakan gambar ini",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Jumlah penggunaan"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Lebar gambar (px)", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tinggi gambar (px)", null=True
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Ukuran file (bytes)", null=True
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Keywords untuk pencarian",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags untuk kategorisasi",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hero_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Image",
                "verbose_name_plural": "Hero Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroImageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Warna untuk kategori",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon untuk kategori",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hero Image Category",
                "verbose_name_plural": "Hero Image Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="herosection",
            name="animation_enabled",
            field=models.BooleanField(default=True, help_text="Enable animations"),
        ),
        migrations.AddField(
            model_name="herosection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_hero_sections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="overlay_opacity",
            field=models.FloatField(
                default=0.5, help_text="Opacity overlay (0.0 - 1.0)"
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="parallax_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable parallax effect"
            ),
        ),
        migrations.CreateModel(
            name="HeroImageUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="Halaman yang menggunakan gambar", max_length=50
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section dalam halaman",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hero_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_history",
                        to="core.heroimage",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Image Usage",
                "verbose_name_plural": "Hero Image Usage History",
                "ordering": ["-used_at"],
            },
        ),
        migrations.AddField(
            model_name="herosection",
            name="background_hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Gambar background dari HeroImage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background_sections",
                to="core.heroimage",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="main_hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Gambar hero utama dari HeroImage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_sections",
                to="core.heroimage",
            ),
        ),
    ]
