# Generated by Django 4.2.7 on 2025-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_heroimage_heroimagecategory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroImageCategory",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="background_hero_image",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="main_hero_image",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="height",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="image_type",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="status",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="usage_count",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="used_in_pages",
        ),
        migrations.RemoveField(
            model_name="heroimage",
            name="width",
        ),
        migrations.AddField(
            model_name="heroimage",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Status aktif"),
        ),
        migrations.AddField(
            model_name="heroimage",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Homepage"),
                    ("population", "Data Penduduk"),
                    ("events", "Kegiatan"),
                    ("news", "Berita"),
                    ("tourism", "Wisata"),
                    ("umkm", "UMKM"),
                    ("organization", "Organisasi"),
                    ("correspondence", "Surat Menyurat"),
                    ("gallery", "Galeri"),
                    ("complaints", "Keluhan"),
                    ("bantuna", "Bantuna"),
                ],
                default="home",
                help_text="Halaman yang menggunakan gambar ini",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="image",
            field=models.ImageField(
                help_text="Gambar hero", upload_to="hero_images/%Y/%m/%d/"
            ),
        ),
        migrations.DeleteModel(
            name="HeroImageUsage",
        ),
        migrations.DeleteModel(
            name="HeroSection",
        ),
    ]
