# Generated by Django 4.2.7 on 2025-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_heroimagecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitesettings",
            name="site_description",
            field=models.TextField(
                blank=True,
                help_text="Deskripsi singkat website yang akan ditampilkan di halaman utama",
                null=True,
            ),
        ),
    ]
