# Generated by Django 4.2.7 on 2025-10-01 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_websitesettings_site_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Homepage"),
                            ("profile", "Profil Desa"),
                            ("population", "Data Penduduk"),
                            ("events", "Kegiatan"),
                            ("news", "Berita"),
                            ("tourism", "Wisata"),
                            ("umkm", "UMKM"),
                            ("organization", "Organisasi"),
                            ("correspondence", "Surat Menyurat"),
                            ("gallery", "Galeri"),
                            ("complaints", "Keluhan"),
                            ("bantuna", "Bantuna"),
                        ],
                        help_text="Halaman yang menggunakan hero section ini",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Gambar hero untuk halaman ini",
                        null=True,
                        upload_to="hero_sections/%Y/%m/%d/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Status aktif"),
                ),
                (
                    "overlay_opacity",
                    models.FloatField(
                        default=0.5, help_text="Opacity overlay (0.0 - 1.0)"
                    ),
                ),
                (
                    "parallax_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable parallax effect"
                    ),
                ),
                (
                    "animation_enabled",
                    models.BooleanField(default=True, help_text="Enable animations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hero_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["page"],
            },
        ),
    ]
