# Generated by Django 4.2.7 on 2025-10-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_herosection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menupermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard"),
                    ("references", "Data Referensi"),
                    ("beneficiaries", "Penerima Bantuan"),
                    ("business", "Usaha"),
                    ("complaints", "Keluhan"),
                    ("documents", "Dokumen"),
                    ("tourism", "Wisata"),
                    ("posyandu", "Posyandu"),
                    ("news", "Berita"),
                    ("village_profile", "Profil Desa"),
                    ("organization", "Organisasi"),
                    ("layanan", "Layanan"),
                    ("reports", "Laporan"),
                    ("settings", "Pengaturan"),
                ],
                max_length=50,
            ),
        ),
    ]
