# Generated by Django 4.2.7 on 2025-10-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_menupermission_module"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeroSection",
        ),
    ]
