# Generated by Django 4.2.7 on 2025-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_hero_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="websitesettings",
            options={
                "verbose_name": "Pengaturan Website",
                "verbose_name_plural": "Pengaturan Website",
            },
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="allow_registration",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="maintenance_mode",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="max_file_upload_size",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="secondary_color",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="site_favicon",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="site_logo",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="sms_notifications",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="timezone",
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="admin_email",
            field=models.EmailField(
                default="admin@pulosarok.desa.id",
                max_length=254,
                verbose_name="Email Admin",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="allowed_document_formats",
            field=models.CharField(
                default="pdf,doc,docx,xls,xlsx",
                max_length=200,
                verbose_name="Format Dokumen Diizinkan",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="allowed_image_formats",
            field=models.CharField(
                default="jpg,jpeg,png,gif,webp",
                max_length=200,
                verbose_name="Format Gambar Diizinkan",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="backup_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Harian"),
                    ("weekly", "Mingguan"),
                    ("monthly", "Bulanan"),
                ],
                default="daily",
                max_length=20,
                verbose_name="Frekuensi Backup",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="backup_retention_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Retensi Backup (hari)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="cache_duration",
            field=models.PositiveIntegerField(
                default=300, verbose_name="Durasi Cache (detik)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="cdn_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL CDN"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="contact_whatsapp",
            field=models.CharField(
                default="0852-1234-5678", max_length=20, verbose_name="WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_auto_backup",
            field=models.BooleanField(default=True, verbose_name="Backup Otomatis"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_cache",
            field=models.BooleanField(default=True, verbose_name="Aktifkan Cache"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_cdn",
            field=models.BooleanField(default=False, verbose_name="Gunakan CDN"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_email_notifications",
            field=models.BooleanField(default=True, verbose_name="Notifikasi Email"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_gzip_compression",
            field=models.BooleanField(default=True, verbose_name="Kompresi GZIP"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_image_compression",
            field=models.BooleanField(
                default=True, verbose_name="Kompresi Gambar Otomatis"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_maintenance_mode",
            field=models.BooleanField(default=False, verbose_name="Mode Maintenance"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_minify_css",
            field=models.BooleanField(default=True, verbose_name="Minify CSS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_minify_js",
            field=models.BooleanField(default=True, verbose_name="Minify JavaScript"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_sms_notifications",
            field=models.BooleanField(default=False, verbose_name="Notifikasi SMS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_ssl_redirect",
            field=models.BooleanField(default=True, verbose_name="Redirect ke HTTPS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="enable_static_cache",
            field=models.BooleanField(default=True, verbose_name="Cache Static Files"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="facebook_pixel_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Facebook Pixel ID"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/favicon/",
                verbose_name="Favicon",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="google_tag_manager_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Google Tag Manager ID",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="image_quality",
            field=models.PositiveIntegerField(
                default=85, verbose_name="Kualitas Gambar (%)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="settings/logo/",
                verbose_name="Logo Website",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="max_login_attempts",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Maksimal Percobaan Login"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="max_upload_size",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Maksimal Ukuran Upload (MB)"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_keywords",
            field=models.CharField(
                default="desa pulosarok, aceh singkil, website desa, pemerintahan desa",
                max_length=500,
                verbose_name="Keywords SEO",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_tagline",
            field=models.CharField(
                default="Desa Digital Terdepan di Aceh Singkil",
                max_length=300,
                verbose_name="Tagline Website",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SMTP Host"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="smtp_password",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SMTP Password"
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, verbose_name="Gunakan TLS"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="smtp_username",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SMTP Username"
            ),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Homepage"),
                    ("events", "Kegiatan"),
                    ("news", "Berita"),
                    ("tourism", "Wisata"),
                    ("umkm", "UMKM"),
                    ("organization", "Organisasi"),
                    ("correspondence", "Surat Menyurat"),
                    ("gallery", "Galeri"),
                    ("complaints", "Keluhan"),
                    ("layanan", "Layanan"),
                    ("posyandu", "Posyandu"),
                    ("bantuna", "Bantuna"),
                ],
                default="home",
                help_text="Halaman yang menggunakan gambar ini",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_address",
            field=models.TextField(
                default="Desa Pulosarok, Kecamatan Singkil, Kabupaten Aceh Singkil, Aceh",
                verbose_name="Alamat Lengkap",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_email",
            field=models.EmailField(
                default="info@pulosarok.desa.id",
                max_length=254,
                verbose_name="Email Kontak",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_phone",
            field=models.CharField(
                default="0852-1234-5678", max_length=20, verbose_name="Nomor Telepon"
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="google_analytics_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Google Analytics ID"
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="maintenance_message",
            field=models.TextField(
                default="Website sedang dalam perbaikan. Terima kasih atas pengertian Anda.",
                verbose_name="Pesan Maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_description",
            field=models.TextField(
                default="Website resmi Desa Pulosarok, Kecamatan Singkil, Kabupaten Aceh Singkil, Aceh",
                verbose_name="Deskripsi Website",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_name",
            field=models.CharField(
                default="Website Desa Pulosarok",
                max_length=200,
                verbose_name="Nama Website",
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, null=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="youtube_url",
            field=models.URLField(blank=True, null=True, verbose_name="YouTube"),
        ),
    ]
