# Generated by Django 4.2.7 on 2025-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_websitesettings_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSettingsDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Website Desa Pulosarok",
                        max_length=200,
                        verbose_name="Nama Website",
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        default="Desa Digital Terdepan di Aceh Singkil",
                        max_length=300,
                        verbose_name="Tagline Website",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="Website resmi Desa Pulosarok, Kecamatan Singkil, Kabupaten Aceh Singkil, Aceh",
                        verbose_name="Deskripsi Website",
                    ),
                ),
                (
                    "site_keywords",
                    models.CharField(
                        default="desa pulosarok, aceh singkil, website desa, pemerintahan desa",
                        max_length=500,
                        verbose_name="Keywords SEO",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        default="0852-1234-5678",
                        max_length=20,
                        verbose_name="Nomor Telepon",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@pulosarok.desa.id",
                        max_length=254,
                        verbose_name="Email Kontak",
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        default="Desa Pulosarok, Kecamatan Singkil, Kabupaten Aceh Singkil, Aceh",
                        verbose_name="Alamat Lengkap",
                    ),
                ),
                (
                    "contact_whatsapp",
                    models.CharField(
                        default="0852-1234-5678", max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, null=True, verbose_name="YouTube"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/logo/",
                        verbose_name="Logo Website",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/favicon/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "enable_cache",
                    models.BooleanField(default=True, verbose_name="Aktifkan Cache"),
                ),
                (
                    "cache_duration",
                    models.PositiveIntegerField(
                        default=300, verbose_name="Durasi Cache (detik)"
                    ),
                ),
                (
                    "enable_static_cache",
                    models.BooleanField(
                        default=True, verbose_name="Cache Static Files"
                    ),
                ),
                (
                    "max_upload_size",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Maksimal Ukuran Upload (MB)"
                    ),
                ),
                (
                    "allowed_image_formats",
                    models.CharField(
                        default="jpg,jpeg,png,gif,webp",
                        max_length=200,
                        verbose_name="Format Gambar Diizinkan",
                    ),
                ),
                (
                    "allowed_document_formats",
                    models.CharField(
                        default="pdf,doc,docx,xls,xlsx",
                        max_length=200,
                        verbose_name="Format Dokumen Diizinkan",
                    ),
                ),
                (
                    "enable_image_compression",
                    models.BooleanField(
                        default=True, verbose_name="Kompresi Gambar Otomatis"
                    ),
                ),
                (
                    "image_quality",
                    models.PositiveIntegerField(
                        default=85, verbose_name="Kualitas Gambar (%)"
                    ),
                ),
                (
                    "enable_maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Mode Maintenance"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        default="Website sedang dalam perbaikan. Terima kasih atas pengertian Anda.",
                        verbose_name="Pesan Maintenance",
                    ),
                ),
                (
                    "enable_ssl_redirect",
                    models.BooleanField(default=True, verbose_name="Redirect ke HTTPS"),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Maksimal Percobaan Login"
                    ),
                ),
                (
                    "enable_gzip_compression",
                    models.BooleanField(default=True, verbose_name="Kompresi GZIP"),
                ),
                (
                    "enable_minify_css",
                    models.BooleanField(default=True, verbose_name="Minify CSS"),
                ),
                (
                    "enable_minify_js",
                    models.BooleanField(default=True, verbose_name="Minify JavaScript"),
                ),
                (
                    "enable_cdn",
                    models.BooleanField(default=False, verbose_name="Gunakan CDN"),
                ),
                (
                    "cdn_url",
                    models.URLField(blank=True, null=True, verbose_name="URL CDN"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Google Tag Manager ID",
                    ),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Facebook Pixel ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="SMTP Host"
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP Port"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SMTP Username",
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SMTP Password",
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="Gunakan TLS"),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(default=True, verbose_name="Notifikasi Email"),
                ),
                (
                    "enable_sms_notifications",
                    models.BooleanField(default=False, verbose_name="Notifikasi SMS"),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        default="admin@pulosarok.desa.id",
                        max_length=254,
                        verbose_name="Email Admin",
                    ),
                ),
                (
                    "enable_auto_backup",
                    models.BooleanField(default=True, verbose_name="Backup Otomatis"),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Harian"),
                            ("weekly", "Mingguan"),
                            ("monthly", "Bulanan"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Frekuensi Backup",
                    ),
                ),
                (
                    "backup_retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Retensi Backup (hari)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pengaturan Website",
                "verbose_name_plural": "Pengaturan Website",
            },
        ),
        migrations.AlterModelOptions(
            name="websitesettings",
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="admin_email",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="allowed_document_formats",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="allowed_image_formats",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="backup_frequency",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="backup_retention_days",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="cache_duration",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="cdn_url",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="contact_whatsapp",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_auto_backup",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_cache",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_cdn",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_email_notifications",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_gzip_compression",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_image_compression",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_maintenance_mode",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_minify_css",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_minify_js",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_sms_notifications",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_ssl_redirect",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="enable_static_cache",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="facebook_pixel_id",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="favicon",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="google_tag_manager_id",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="image_quality",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="max_login_attempts",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="max_upload_size",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="site_keywords",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="site_tagline",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="smtp_host",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="smtp_password",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="smtp_port",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="smtp_use_tls",
        ),
        migrations.RemoveField(
            model_name="websitesettings",
            name="smtp_username",
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="allow_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="default_language",
            field=models.CharField(
                choices=[
                    ("id", "Bahasa Indonesia"),
                    ("en", "English"),
                    ("jv", "Bahasa Jawa"),
                ],
                default="id",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="max_file_upload_size",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="meta_keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="primary_color",
            field=models.CharField(default="#3B82F6", max_length=7),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="secondary_color",
            field=models.CharField(default="#10B981", max_length=7),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_favicon",
            field=models.ImageField(blank=True, null=True, upload_to="website/"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="site_logo",
            field=models.ImageField(blank=True, null=True, upload_to="website/"),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light Theme"),
                    ("dark", "Dark Theme"),
                    ("auto", "Auto (System)"),
                ],
                default="light",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="timezone",
            field=models.CharField(default="Asia/Jakarta", max_length=50),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="google_analytics_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="maintenance_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_description",
            field=models.TextField(
                blank=True,
                help_text="Deskripsi singkat website yang akan ditampilkan di halaman utama",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="site_name",
            field=models.CharField(default="Website Desa Pulosarok", max_length=200),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
