# Generated by Django 4.2.16 on 2025-10-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_websitesettingsduplicate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_id",
            field=models.CharField(
                blank=True,
                help_text="Secure unique profile identifier",
                max_length=64,
                unique=True,
            ),
        ),
    ]
