# Generated by Django 4.2.16 on 2025-10-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroimage",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Homepage"),
                    ("events", "Kegiatan"),
                    ("news", "Berita"),
                    ("tourism", "Wisata"),
                    ("umkm", "UMKM"),
                    ("organization", "Organisasi"),
                    ("correspondence", "Surat Menyurat"),
                    ("gallery", "Galeri"),
                    ("complaints", "Keluhan"),
                    ("layanan", "Layanan"),
                    ("posyandu", "Posyandu"),
                    ("bantuna", "Bantuna"),
                    ("business", "Bisnis"),
                    ("koperasi", "Koperasi"),
                    ("bumg", "BUMG"),
                    ("layanan_jasa", "Layanan Jasa"),
                ],
                default="home",
                help_text="Halaman yang menggunakan gambar ini",
                max_length=20,
            ),
        ),
    ]
