# Generated by Django 4.2.16 on 2025-10-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0007_alter_pelajar_tahun_masuk"),
        ("beneficiaries", "0002_penduduk_alter_beneficiary_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiary_records",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="databantuan",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_bantuan",
                to="references.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="tarafkehidupan",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taraf_kehidupan",
                to="references.penduduk",
            ),
        ),
        migrations.DeleteModel(
            name="Penduduk",
        ),
    ]
