# Generated by Django 4.2.7 on 2025-09-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posyandulocation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="posyandu/locations/"
            ),
        ),
    ]
