# Generated by Django 4.2.7 on 2025-09-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0002_posyandulocation_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="posyandulocation",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="posyandulocation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posyandulocation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="posyandulocation",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="posyandulocation",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="posyandulocation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
