# Generated by Django 4.2.7 on 2025-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posyandu",
            "0003_posyandulocation_code_posyandulocation_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "age_min",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum age in years", null=True
                    ),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum age in years", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Pasien",
                "verbose_name_plural": "Jenis Pasien",
                "ordering": ["name"],
            },
        ),
    ]
