# Generated by Django 4.2.7 on 2025-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0004_patienttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuntingdata",
            name="z_score_tb_u",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Z-Score Tinggi Badan menurut Umur",
                max_digits=5,
                null=True,
            ),
        ),
    ]
