# Generated by Django 4.2.7 on 2025-09-20 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posyandu", "0005_alter_stuntingdata_z_score_tb_u"),
    ]

    operations = [
        migrations.RenameField(
            model_name="immunization",
            old_name="expiry_date",
            new_name="next_schedule",
        ),
        migrations.RemoveField(
            model_name="immunization",
            name="administered_by",
        ),
        migrations.RemoveField(
            model_name="immunization",
            name="dose_number",
        ),
        migrations.RemoveField(
            model_name="immunization",
            name="next_dose_date",
        ),
        migrations.RemoveField(
            model_name="immunization",
            name="side_effects",
        ),
        migrations.RemoveField(
            model_name="immunization",
            name="vaccine_name",
        ),
        migrations.AddField(
            model_name="immunization",
            name="health_worker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="immunization",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="immunization",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="immunization",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Selesai"),
                    ("pending", "Menunggu"),
                    ("overdue", "Terlambat"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="immunization",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="immunization",
            name="vaccine_type",
            field=models.CharField(
                choices=[
                    ("bcg", "BCG"),
                    ("hepatitis", "Hepatitis B"),
                    ("polio", "Polio"),
                    ("dpt", "DPT"),
                    ("campak", "Campak"),
                    ("other", "Lainnya"),
                ],
                max_length=20,
            ),
        ),
    ]
