# Generated by Django 4.2.16 on 2025-10-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0006_rename_expiry_date_immunization_next_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penduduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nik", models.CharField(max_length=16, unique=True)),
                ("alamat", models.TextField(blank=True)),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Penduduk",
            },
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_records",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="ibuhamil",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kehamilan",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="immunization",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="immunizations",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="nutritiondata",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_data",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="posyandukader",
            name="penduduk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kader_posyandu",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="posyandulocation",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_posyandu",
                to="posyandu.penduduk",
            ),
        ),
        migrations.AlterField(
            model_name="stuntingdata",
            name="balita",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stunting_data",
                to="posyandu.penduduk",
            ),
        ),
    ]
