# Generated by Django 5.2.6 on 2025-09-12 23:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Jenis Surat"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode Surat"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx", "pdf"]
                            )
                        ],
                        verbose_name="File Template",
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        blank=True,
                        help_text="Dokumen yang diperlukan (pisahkan dengan koma)",
                        verbose_name="Dokumen yang Diperlukan",
                    ),
                ),
                (
                    "processing_time_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Waktu Proses (Hari)"
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Biaya"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Surat",
                "verbose_name_plural": "Jenis Surat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="APIKeySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nama Layanan"
                    ),
                ),
                ("api_key", models.TextField(verbose_name="API Key (Encrypted)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "max_requests_per_day",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Maksimal Request per Hari"
                    ),
                ),
                (
                    "current_usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Penggunaan Hari Ini"
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Tanggal Reset Terakhir"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan API Key",
                "verbose_name_plural": "Pengaturan API Key",
                "ordering": ["service_name"],
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Nomor Surat",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Perihal")),
                ("content", models.TextField(verbose_name="Isi Surat")),
                ("purpose", models.TextField(verbose_name="Tujuan Penggunaan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Diajukan"),
                            ("in_review", "Sedang Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Persetujuan"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Alasan Penolakan"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "ai_generated_content",
                    models.TextField(
                        blank=True, verbose_name="Konten yang Dihasilkan AI"
                    ),
                ),
                (
                    "ai_suggestions_applied",
                    models.TextField(
                        default="[]", verbose_name="Saran AI yang Diterapkan"
                    ),
                ),
                (
                    "requires_ai_validation",
                    models.BooleanField(
                        default=True, verbose_name="Memerlukan Validasi AI"
                    ),
                ),
                (
                    "requires_digital_signature",
                    models.BooleanField(
                        default=False, verbose_name="Memerlukan Tanda Tangan Digital"
                    ),
                ),
                (
                    "is_digitally_signed",
                    models.BooleanField(
                        default=False, verbose_name="Sudah Ditandatangani Digital"
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        verbose_name="Hash Dokumen untuk Tanda Tangan",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_pdfs/",
                        verbose_name="File PDF",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="letter_qrcodes/",
                        verbose_name="QR Code untuk Verifikasi",
                    ),
                ),
                (
                    "public_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL Publik",
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah Kata"),
                ),
                (
                    "estimated_reading_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Estimasi Waktu Baca (detik)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="id", max_length=10, verbose_name="Bahasa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                        verbose_name="Pemohon",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disetujui Oleh",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surat",
                "verbose_name_plural": "Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterAIValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="ID Validasi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("processing", "Sedang Diproses"),
                            ("completed", "Selesai"),
                            ("failed", "Gagal"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status Validasi",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Skor Kepercayaan (0-1)"
                    ),
                ),
                (
                    "validation_result",
                    models.TextField(default="{}", verbose_name="Hasil Validasi"),
                ),
                (
                    "suggestions",
                    models.TextField(default="[]", verbose_name="Saran Perbaikan"),
                ),
                (
                    "grammar_check",
                    models.TextField(
                        default="{}", verbose_name="Pemeriksaan Tata Bahasa"
                    ),
                ),
                (
                    "content_analysis",
                    models.TextField(default="{}", verbose_name="Analisis Konten"),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Waktu Proses (ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Pesan Error"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Validasi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_validation",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validasi AI Surat",
                "verbose_name_plural": "Validasi AI Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("supporting_document", "Dokumen Pendukung"),
                            ("identity_card", "Kartu Identitas"),
                            ("certificate", "Sertifikat"),
                            ("photo", "Foto"),
                            ("other", "Lainnya"),
                        ],
                        max_length=30,
                        verbose_name="Jenis Lampiran",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Lampiran"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "file",
                    models.FileField(
                        upload_to="letter_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ukuran File (bytes)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Wajib"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diunggah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lampiran Surat",
                "verbose_name_plural": "Lampiran Surat",
                "ordering": ["-is_required", "title"],
            },
        ),
        migrations.CreateModel(
            name="LetterRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "Eksternal"),
                            ("government", "Instansi Pemerintah"),
                            ("private", "Swasta"),
                            ("individual", "Perorangan"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Penerima",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nama Penerima"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jabatan"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organisasi/Instansi"
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telepon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Penerima Utama"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("hand_delivery", "Antar Langsung"),
                            ("post", "Pos"),
                            ("email", "Email"),
                            ("fax", "Fax"),
                        ],
                        default="hand_delivery",
                        max_length=20,
                        verbose_name="Metode Pengiriman",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengiriman"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Diterima"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penerima Surat",
                "verbose_name_plural": "Penerima Surat",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="LetterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(
                        default="Desa Pulosarok",
                        max_length=100,
                        verbose_name="Nama Desa",
                    ),
                ),
                (
                    "village_address",
                    models.TextField(
                        default="Kecamatan Pulosarok, Kabupaten Indramayu",
                        verbose_name="Alamat Desa",
                    ),
                ),
                (
                    "village_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telepon Desa"
                    ),
                ),
                (
                    "village_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Desa"
                    ),
                ),
                (
                    "village_website",
                    models.URLField(blank=True, verbose_name="Website Desa"),
                ),
                (
                    "village_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_settings/",
                        verbose_name="Logo Desa",
                    ),
                ),
                (
                    "head_of_village_name",
                    models.CharField(max_length=100, verbose_name="Nama Kepala Desa"),
                ),
                (
                    "head_of_village_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Kepala Desa"
                    ),
                ),
                (
                    "head_of_village_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Teks Tanda Tangan"
                    ),
                ),
                (
                    "secretary_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nama Sekretaris Desa"
                    ),
                ),
                (
                    "secretary_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Sekretaris"
                    ),
                ),
                (
                    "secretary_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "secretary_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "letter_number_format",
                    models.CharField(
                        default="{code}/{number:03d}/{month:02d}/{year}",
                        help_text="Gunakan {code}, {number}, {month}, {year} sebagai placeholder",
                        max_length=100,
                        verbose_name="Format Nomor Surat",
                    ),
                ),
                (
                    "current_year_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Counter Tahun Ini"
                    ),
                ),
                (
                    "reset_counter_yearly",
                    models.BooleanField(
                        default=True, verbose_name="Reset Counter Setiap Tahun"
                    ),
                ),
                (
                    "enable_ai_validation",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Validasi AI"
                    ),
                ),
                (
                    "ai_validation_threshold",
                    models.FloatField(
                        default=0.8, verbose_name="Threshold Validasi AI (0-1)"
                    ),
                ),
                (
                    "enable_ai_suggestions",
                    models.BooleanField(default=True, verbose_name="Aktifkan Saran AI"),
                ),
                (
                    "enable_digital_signature",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Tanda Tangan Digital"
                    ),
                ),
                (
                    "signature_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Sertifikat Digital",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Surat",
                "verbose_name_plural": "Pengaturan Surat",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Template"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("official", "Surat Resmi"),
                            ("certificate", "Surat Keterangan"),
                            ("recommendation", "Surat Rekomendasi"),
                            ("invitation", "Surat Undangan"),
                            ("notification", "Surat Pemberitahuan"),
                            ("custom", "Template Kustom"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Template",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "content_template",
                    models.TextField(
                        help_text="Gunakan {{variable}} untuk placeholder",
                        verbose_name="Template Konten",
                    ),
                ),
                (
                    "variables",
                    models.TextField(
                        default="{}",
                        help_text="JSON object dengan daftar variabel yang tersedia",
                        verbose_name="Variabel Template",
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True,
                        help_text="CSS untuk styling template",
                        verbose_name="CSS Styles",
                    ),
                ),
                (
                    "header_template",
                    models.TextField(blank=True, verbose_name="Template Header"),
                ),
                (
                    "footer_template",
                    models.TextField(blank=True, verbose_name="Template Footer"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Template Default"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Penggunaan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Surat",
                "verbose_name_plural": "Template Surat",
                "ordering": ["-is_default", "-usage_count", "name"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="letters.lettertemplate",
                verbose_name="Template Surat",
            ),
        ),
        migrations.CreateModel(
            name="LetterTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Dibuat"),
                            ("submitted", "Diajukan"),
                            ("reviewed", "Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Diselesaikan"),
                            ("cancelled", "Dibatalkan"),
                            ("sent", "Dikirim"),
                            ("received", "Diterima"),
                            ("returned", "Dikembalikan"),
                        ],
                        max_length=20,
                        verbose_name="Aksi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lokasi"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Alamat IP"
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dilakukan Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Surat",
                "verbose_name_plural": "Tracking Surat",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="letter_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="letters.lettertype",
                verbose_name="Jenis Surat",
            ),
        ),
        migrations.CreateModel(
            name="LetterDigitalSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(max_length=256, verbose_name="Hash Tanda Tangan"),
                ),
                (
                    "signature_data",
                    models.TextField(verbose_name="Data Tanda Tangan (Encrypted)"),
                ),
                (
                    "certificate_info",
                    models.TextField(default="{}", verbose_name="Informasi Sertifikat"),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Waktu Tanda Tangan"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Alamat IP")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("signed", "Ditandatangani"),
                            ("verified", "Terverifikasi"),
                            ("invalid", "Tidak Valid"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Verifikasi"
                    ),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="Valid")),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_signatures",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penandatangan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tanda Tangan Digital",
                "verbose_name_plural": "Tanda Tangan Digital",
                "ordering": ["-signature_timestamp"],
                "unique_together": {("letter", "signer")},
            },
        ),
    ]
