# Generated by Django 4.2.16 on 2025-10-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0007_alter_pelajar_tahun_masuk"),
        ("letters", "0002_penduduk_alter_letter_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="references.penduduk",
                verbose_name="Pemohon",
            ),
        ),
        migrations.DeleteModel(
            name="Penduduk",
        ),
    ]
