# Generated by Django 4.2.16 on 2025-10-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0003_alter_letter_applicant_delete_penduduk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="letter",
            name="ai_generated_content",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="ai_suggestions_applied",
        ),
        migrations.RemoveField(
            model_name="letter",
            name="requires_ai_validation",
        ),
        migrations.RemoveField(
            model_name="lettersettings",
            name="ai_validation_threshold",
        ),
        migrations.RemoveField(
            model_name="lettersettings",
            name="enable_ai_suggestions",
        ),
        migrations.RemoveField(
            model_name="lettersettings",
            name="enable_ai_validation",
        ),
        migrations.DeleteModel(
            name="LetterAIValidation",
        ),
    ]
