# Generated by Django 4.2.7 on 2025-09-18 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0002_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentIncomingOutgoing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("masuk", "Dokumen Masuk"),
                            ("keluar", "Dokumen Keluar"),
                            ("internal", "Dokumen Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("document_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Diproses"),
                            ("completed", "Selesai"),
                            ("archived", "Arsip"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, upload_to="documents/incoming_outgoing/"
                    ),
                ),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Tags separated by comma"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_outgoing_documents",
                        to="documents.documenttype",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_outgoing_documents",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Masuk/Keluar",
                "verbose_name_plural": "Dokumen Masuk/Keluar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Dibuat"),
                            ("uploaded", "Diupload"),
                            ("viewed", "Dilihat"),
                            ("downloaded", "Didownload"),
                            ("updated", "Diupdate"),
                            ("deleted", "Dihapus"),
                            ("archived", "Diarsipkan"),
                            ("restored", "Dipulihkan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_records",
                        to="documents.documentincomingoutgoing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Dokumen",
                "verbose_name_plural": "Tracking Dokumen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archive_reason", models.TextField()),
                ("archive_date", models.DateTimeField(auto_now_add=True)),
                ("restore_date", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_records",
                        to="documents.documentincomingoutgoing",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Arsip Dokumen",
                "verbose_name_plural": "Arsip Dokumen",
                "ordering": ["-archive_date"],
            },
        ),
    ]
