# Generated by Django 4.2.7 on 2025-09-27 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_documentincomingoutgoing_documenttracking_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pengaturan Dokumen",
                "verbose_name_plural": "Pengaturan Dokumen",
            },
        ),
        migrations.CreateModel(
            name="VillageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="DESA PULOSAROK", max_length=200)),
                (
                    "address",
                    models.TextField(
                        default="Kecamatan Pulosarok, Kabupaten Luwu Timur"
                    ),
                ),
                ("postal_code", models.CharField(default="92985", max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="village/")),
                (
                    "head_name",
                    models.CharField(default="Kepala Desa Pulosarok", max_length=100),
                ),
                ("head_nip", models.CharField(blank=True, max_length=20)),
                (
                    "head_signature",
                    models.ImageField(blank=True, upload_to="signatures/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Informasi Desa",
                "verbose_name_plural": "Informasi Desa",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "ordering": ["name"],
                "verbose_name": "Jenis Dokumen",
                "verbose_name_plural": "Jenis Dokumen",
            },
        ),
        migrations.AddField(
            model_name="documenttype",
            name="auto_generate_number",
            field=models.BooleanField(
                default=True, help_text="Generate nomor dokumen otomatis"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="category",
            field=models.CharField(
                blank=True, help_text="Kategori dokumen", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="number_prefix",
            field=models.CharField(
                blank=True, help_text="Prefix untuk nomor dokumen", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="qr_code_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable QR code pada dokumen"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="signature_required",
            field=models.BooleanField(
                default=True, help_text="Apakah dokumen memerlukan tanda tangan"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="template_required",
            field=models.BooleanField(
                default=True, help_text="Apakah dokumen memerlukan template"
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="workflow_required",
            field=models.BooleanField(
                default=False, help_text="Apakah dokumen memerlukan workflow approval"
            ),
        ),
        migrations.CreateModel(
            name="DocumentWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="documents.documenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Dokumen",
                "verbose_name_plural": "Workflow Dokumen",
            },
        ),
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(blank=True, upload_to="signatures/"),
                ),
                (
                    "signature_data",
                    models.TextField(blank=True, help_text="Digital signature data"),
                ),
                ("position", models.CharField(default="Kepala Desa", max_length=100)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="documents.document",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tanda Tangan Dokumen",
                "verbose_name_plural": "Tanda Tangan Dokumen",
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Harian"),
                            ("weekly", "Mingguan"),
                            ("monthly", "Bulanan"),
                            ("yearly", "Tahunan"),
                            ("custom", "Kustom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status_filter", models.CharField(blank=True, max_length=20)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_types",
                    models.ManyToManyField(blank=True, to="documents.documenttype"),
                ),
            ],
            options={
                "verbose_name": "Laporan Dokumen",
                "verbose_name_plural": "Laporan Dokumen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("document_created", "Dokumen Dibuat"),
                            ("document_submitted", "Dokumen Diajukan"),
                            ("document_approved", "Dokumen Disetujui"),
                            ("document_rejected", "Dokumen Ditolak"),
                            ("document_completed", "Dokumen Selesai"),
                            ("workflow_step", "Step Workflow"),
                            ("deadline_reminder", "Pengingat Deadline"),
                            ("system_alert", "Alert Sistem"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="documents.document",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifikasi Dokumen",
                "verbose_name_plural": "Notifikasi Dokumen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Komentar internal (tidak terlihat oleh pemohon)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentar Dokumen",
                "verbose_name_plural": "Komentar Dokumen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False, help_text="Auto approve jika kondisi terpenuhi"
                    ),
                ),
                (
                    "conditions",
                    models.TextField(
                        blank=True, help_text="Kondisi untuk auto approve (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.documentworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step Workflow",
                "verbose_name_plural": "Step Workflow",
                "ordering": ["workflow", "step_number"],
                "unique_together": {("workflow", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "changes",
                    models.TextField(blank=True, help_text="Deskripsi perubahan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versi Dokumen",
                "verbose_name_plural": "Versi Dokumen",
                "ordering": ["document", "-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
    ]
