# Generated by Django 4.2.16 on 2025-10-05 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layanan", "0004_alter_layanandocumentrequest_document_type"),
        ("references", "0007_alter_pelajar_tahun_masuk"),
        ("documents", "0005_penduduk_alter_document_applicant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lampiran Dokumen",
                "verbose_name_plural": "Lampiran Dokumen",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Dokumen",
                "verbose_name_plural": "Kategori Dokumen",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="documentapproval",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentapproval",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="documentapproval",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentarchive",
            name="archived_by",
        ),
        migrations.RemoveField(
            model_name="documentarchive",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentarchive",
            name="restored_by",
        ),
        migrations.RemoveField(
            model_name="documentincomingoutgoing",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentincomingoutgoing",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documentincomingoutgoing",
            name="resident",
        ),
        migrations.RemoveField(
            model_name="documentnotification",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentnotification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="documentnotification",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="documentreport",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentreport",
            name="document_types",
        ),
        migrations.RemoveField(
            model_name="documentrequest",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documentrequest",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="documentrequest",
            name="requester",
        ),
        migrations.DeleteModel(
            name="DocumentSettings",
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="signer",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documenttracking",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documenttracking",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentworkflow",
            name="document_type",
        ),
        migrations.AlterUniqueTogether(
            name="documentworkflowstep",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentworkflowstep",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="documentworkflowstep",
            name="workflow",
        ),
        migrations.DeleteModel(
            name="VillageInfo",
        ),
        migrations.RemoveField(
            model_name="document",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documentcomment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("surat_warga", "Surat dari Warga"),
                    ("surat_masuk", "Surat Masuk"),
                    ("surat_keluar", "Surat Keluar"),
                    ("surat_internal", "Surat Internal"),
                ],
                default="surat_warga",
                max_length=20,
                verbose_name="Kategori",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Tanggal Dokumen"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="recipient",
            field=models.CharField(blank=True, max_length=200, verbose_name="Penerima"),
        ),
        migrations.AddField(
            model_name="document",
            name="sender",
            field=models.CharField(blank=True, max_length=200, verbose_name="Pengirim"),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Ringkasan"),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Pisahkan dengan koma",
                max_length=500,
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="references.penduduk",
                verbose_name="Pemohon",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="completion_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tanggal Selesai"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(verbose_name="Isi Dokumen"),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nomor Dokumen"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_attachment",
            field=models.FileField(
                blank=True, upload_to="documents/", verbose_name="Lampiran"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Catatan"),
        ),
        migrations.AlterField(
            model_name="document",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Rendah"),
                    ("normal", "Normal"),
                    ("high", "Tinggi"),
                    ("urgent", "Mendesak"),
                ],
                default="normal",
                max_length=10,
                verbose_name="Prioritas",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Diajukan"),
                    ("approved", "Disetujui"),
                    ("rejected", "Ditolak"),
                    ("completed", "Selesai"),
                    ("archived", "Diarsipkan"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="submission_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tanggal Diajukan"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Judul Dokumen"),
        ),
        migrations.AlterField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Diupdate Pada"),
        ),
        migrations.AlterField(
            model_name="documentcomment",
            name="comment",
            field=models.TextField(verbose_name="Komentar"),
        ),
        migrations.AlterField(
            model_name="documentcomment",
            name="is_internal",
            field=models.BooleanField(default=False, verbose_name="Komentar Internal"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category", "status"], name="documents_d_categor_00522f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_date"], name="documents_d_documen_0eb394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_d_created_3b0a51_idx"
            ),
        ),
        migrations.DeleteModel(
            name="DocumentApproval",
        ),
        migrations.DeleteModel(
            name="DocumentArchive",
        ),
        migrations.DeleteModel(
            name="DocumentIncomingOutgoing",
        ),
        migrations.DeleteModel(
            name="DocumentNotification",
        ),
        migrations.DeleteModel(
            name="DocumentReport",
        ),
        migrations.DeleteModel(
            name="DocumentRequest",
        ),
        migrations.DeleteModel(
            name="DocumentSignature",
        ),
        migrations.DeleteModel(
            name="DocumentTemplate",
        ),
        migrations.DeleteModel(
            name="DocumentTracking",
        ),
        migrations.DeleteModel(
            name="DocumentType",
        ),
        migrations.DeleteModel(
            name="DocumentVersion",
        ),
        migrations.DeleteModel(
            name="DocumentWorkflow",
        ),
        migrations.DeleteModel(
            name="DocumentWorkflowStep",
        ),
        migrations.DeleteModel(
            name="Penduduk",
        ),
        migrations.AddField(
            model_name="documentattachment",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.documentcategory",
                verbose_name="Kategori Dokumen",
            ),
        ),
    ]
