# Generated by Django 4.2.16 on 2025-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_documentattachment_documentcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, verbose_name="Isi Dokumen"),
        ),
    ]
