# Generated by Django 4.2.16 on 2025-10-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0007_alter_pelajar_tahun_masuk"),
    ]

    operations = [
        migrations.CreateModel(
            name="BUMG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nomor_sk", models.CharField(blank=True, max_length=100)),
                ("tanggal_sk", models.DateField()),
                ("alamat", models.TextField()),
                ("direktur", models.CharField(max_length=100)),
                ("komisaris", models.CharField(blank=True, max_length=100)),
                (
                    "modal_dasar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "modal_disetor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("bidang_usaha", models.TextField()),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Menunggu Persetujuan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BUMG",
                "verbose_name_plural": "BUMG",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("umkm", "UMKM"),
                            ("koperasi", "Koperasi"),
                            ("bumg", "BUMG"),
                            ("layanan_jasa", "Layanan Jasa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Persetujuan"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("inactive", "Tidak Aktif"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bisnis",
                "verbose_name_plural": "Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Bisnis",
                "verbose_name_plural": "Kategori Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessPageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="business_headers/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Header Halaman Bisnis",
                "verbose_name_plural": "Header Halaman Bisnis",
            },
        ),
        migrations.CreateModel(
            name="JenisKoperasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
                ("deskripsi", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Koperasi",
                "verbose_name_plural": "Jenis Koperasi",
            },
        ),
        migrations.CreateModel(
            name="Koperasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        default="Koperasi", max_length=200, verbose_name="Nama Koperasi"
                    ),
                ),
                ("ketua", models.CharField(max_length=200)),
                ("sekretaris", models.CharField(blank=True, max_length=200)),
                ("bendahara", models.CharField(blank=True, max_length=200)),
                ("alamat", models.TextField()),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("tanggal_berdiri", models.DateField()),
                ("nomor_badan_hukum", models.CharField(blank=True, max_length=100)),
                (
                    "jenis_koperasi",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jenis Koperasi"
                    ),
                ),
                ("jumlah_anggota", models.PositiveIntegerField(default=0)),
                (
                    "modal_dasar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Modal Dasar",
                    ),
                ),
                (
                    "modal_disetor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Modal Disetor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Menunggu Persetujuan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Koperasi",
                "verbose_name_plural": "Koperasi",
            },
        ),
        migrations.CreateModel(
            name="LayananJasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200, verbose_name="Nama Layanan")),
                ("penyedia", models.CharField(max_length=200)),
                ("alamat", models.TextField()),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kategori",
                    models.CharField(max_length=200, verbose_name="Kategori Layanan"),
                ),
                ("deskripsi", models.TextField(verbose_name="Deskripsi Layanan")),
                (
                    "deskripsi_layanan",
                    models.TextField(
                        blank=True, verbose_name="Deskripsi Layanan (Lama)"
                    ),
                ),
                (
                    "tarif_layanan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Tarif Layanan",
                    ),
                ),
                (
                    "jam_operasional",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jam Operasional"
                    ),
                ),
                (
                    "pengalaman",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pengalaman"
                    ),
                ),
                (
                    "harga_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Harga Minimum",
                    ),
                ),
                (
                    "harga_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Harga Maksimum",
                    ),
                ),
                (
                    "satuan_harga",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Satuan Harga"
                    ),
                ),
                (
                    "waktu_layanan",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Waktu Layanan"
                    ),
                ),
                (
                    "area_layanan",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Area Layanan"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=3, verbose_name="Rating"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("keunggulan", models.TextField(blank=True, verbose_name="Keunggulan")),
                (
                    "syarat_ketentuan",
                    models.TextField(blank=True, verbose_name="Syarat & Ketentuan"),
                ),
                (
                    "sertifikat",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sertifikat"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Menunggu Persetujuan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Layanan Jasa",
                "verbose_name_plural": "Layanan Jasa",
            },
        ),
        migrations.CreateModel(
            name="UKM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_usaha", models.CharField(max_length=200)),
                ("pemilik", models.CharField(max_length=200)),
                ("nik_pemilik", models.CharField(blank=True, max_length=16)),
                ("jenis_usaha", models.CharField(max_length=200)),
                (
                    "skala_usaha",
                    models.CharField(
                        choices=[
                            ("mikro", "Mikro"),
                            ("kecil", "Kecil"),
                            ("menengah", "Menengah"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tanggal_mulai", models.DateField()),
                ("nomor_izin", models.CharField(blank=True, max_length=100)),
                ("alamat_usaha", models.TextField()),
                ("alamat_pemilik", models.TextField()),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "modal_awal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "omzet_bulanan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("jumlah_karyawan", models.PositiveIntegerField(default=0)),
                ("produk_utama", models.TextField()),
                ("target_pasar", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Menunggu Persetujuan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UMKM",
                "verbose_name_plural": "UMKM",
            },
        ),
        migrations.CreateModel(
            name="BusinessProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produk Bisnis",
                "verbose_name_plural": "Produk Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="business.business",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemilik Bisnis",
                "verbose_name_plural": "Pemilik Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keuangan Bisnis",
                "verbose_name_plural": "Keuangan Bisnis",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businesses",
                to="business.businesscategory",
            ),
        ),
        migrations.CreateModel(
            name="Aset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aset",
                "verbose_name_plural": "Aset",
            },
        ),
    ]
