# Generated by Django 5.2.6 on 2025-09-12 23:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Intent"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Intent Chat",
                "verbose_name_plural": "Intent Chat",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nama Pengguna"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Pengguna"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sesi Chat",
                "verbose_name_plural": "Sesi Chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Kategori"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Pengaduan",
                "verbose_name_plural": "Kategori Pengaduan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChatPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=200, verbose_name="Pattern")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to="complaints.chatintent",
                        verbose_name="Intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern Chat",
                "verbose_name_plural": "Pattern Chat",
            },
        ),
        migrations.CreateModel(
            name="ChatResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField(verbose_name="Response")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="complaints.chatintent",
                        verbose_name="Intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Response Chat",
                "verbose_name_plural": "Response Chat",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "Pengguna"),
                            ("bot", "Bot"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                        verbose_name="Tipe Pesan",
                    ),
                ),
                ("content", models.TextField(verbose_name="Isi Pesan")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Sudah Dibaca"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="complaints.chatsession",
                        verbose_name="Sesi Chat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesan Chat",
                "verbose_name_plural": "Pesan Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID Pengaduan",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(max_length=200, verbose_name="Nama Pelapor"),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Pelapor",
                    ),
                ),
                (
                    "reporter_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "reporter_address",
                    models.TextField(blank=True, verbose_name="Alamat Pelapor"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Pengaduan"),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Pengaduan")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lokasi Kejadian"
                    ),
                ),
                (
                    "incident_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Kejadian"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("in_review", "Sedang Ditinjau"),
                            ("in_progress", "Sedang Diproses"),
                            ("resolved", "Selesai"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("medium", "Sedang"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="complaints/attachments/",
                        verbose_name="File Lampiran",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Catatan Admin"),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, verbose_name="Penyelesaian"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diperbarui"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Feedback Pelapor"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ditugaskan Kepada",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="complaints.complaintcategory",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaduan",
                "verbose_name_plural": "Pengaduan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("in_review", "Sedang Ditinjau"),
                            ("in_progress", "Sedang Diproses"),
                            ("resolved", "Selesai"),
                            ("rejected", "Ditolak"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.TextField(verbose_name="Pesan Update")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Update"
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="complaints.complaint",
                        verbose_name="Pengaduan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diperbarui Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Update Pengaduan",
                "verbose_name_plural": "Update Pengaduan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID Kontak",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=200, verbose_name="Nama Pengirim"),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Pengirim",
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Anonim"),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("general", "Pertanyaan Umum"),
                            ("service", "Layanan Desa"),
                            ("complaint", "Keluhan"),
                            ("suggestion", "Saran"),
                            ("information", "Permintaan Informasi"),
                            ("other", "Lainnya"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Jenis Subjek",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subjek")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("read", "Sudah Dibaca"),
                            ("replied", "Sudah Dibalas"),
                            ("closed", "Ditutup"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Catatan Admin"),
                ),
                ("reply_message", models.TextField(blank=True, verbose_name="Balasan")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diperbarui"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dibaca"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dibalas"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ditugaskan Kepada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesan Kontak",
                "verbose_name_plural": "Pesan Kontak",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("complaint_new", "Pengaduan Baru"),
                            ("complaint_update", "Update Pengaduan"),
                            ("complaint_resolved", "Pengaduan Selesai"),
                            ("chat_new", "Chat Baru"),
                            ("system", "Sistem"),
                        ],
                        max_length=20,
                        verbose_name="Tipe Notifikasi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Email Penerima"),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Sudah Dikirim"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dikirim"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="complaints.chatsession",
                        verbose_name="Sesi Chat",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="complaints.complaint",
                        verbose_name="Pengaduan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifikasi",
                "verbose_name_plural": "Notifikasi",
                "ordering": ["-created_at"],
            },
        ),
    ]
