# Generated by Django 4.2.16 on 2025-10-05 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("initial", "Verifikasi Awal"),
                            ("field", "Verifikasi Lapangan"),
                            ("document", "Verifikasi Dokumen"),
                            ("follow_up", "Tindak Lanjut"),
                            ("final", "Verifikasi Final"),
                        ],
                        default="initial",
                        max_length=20,
                        verbose_name="Jenis Verifikasi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("in_progress", "Sedang Diverifikasi"),
                            ("verified", "Terverifikasi"),
                            ("rejected", "Ditolak"),
                            ("requires_info", "Memerlukan Informasi Tambahan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status Verifikasi",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(verbose_name="Catatan Verifikasi"),
                ),
                (
                    "verification_result",
                    models.TextField(blank=True, verbose_name="Hasil Verifikasi"),
                ),
                (
                    "supporting_evidence",
                    models.TextField(blank=True, verbose_name="Bukti Pendukung"),
                ),
                (
                    "recommended_action",
                    models.TextField(blank=True, verbose_name="Rekomendasi Tindakan"),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("medium", "Sedang"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Tingkat Prioritas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diperbarui"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Diverifikasi"
                    ),
                ),
                (
                    "requires_follow_up",
                    models.BooleanField(
                        default=False, verbose_name="Memerlukan Tindak Lanjut"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Tindak Lanjut"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(blank=True, verbose_name="Catatan Tindak Lanjut"),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="complaints.complaint",
                        verbose_name="Pengaduan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diverifikasi Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verifikasi Pengaduan",
                "verbose_name_plural": "Verifikasi Pengaduan",
                "ordering": ["-created_at"],
            },
        ),
    ]
