# Generated by Django 5.2.6 on 2025-09-12 23:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VillageProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Desa")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode Desa"
                    ),
                ),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Kecamatan"),
                ),
                ("regency", models.CharField(max_length=100, verbose_name="Kabupaten")),
                ("province", models.CharField(max_length=100, verbose_name="Provinsi")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Kode Pos"),
                ),
                (
                    "village_head",
                    models.CharField(max_length=100, verbose_name="Kepala Desa"),
                ),
                ("established_date", models.DateField(verbose_name="Tanggal Berdiri")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Luas Wilayah (km²)",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Desa")),
                (
                    "profile_description",
                    models.TextField(
                        blank=True,
                        help_text="Deskripsi singkat profil desa yang akan ditampilkan di bagian atas",
                        null=True,
                        verbose_name="Profil Desa",
                    ),
                ),
                ("vision", models.TextField(verbose_name="Visi")),
                (
                    "mission",
                    models.TextField(
                        help_text="Pisahkan setiap misi dengan baris baru",
                        verbose_name="Misi",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_profile/logo/",
                        verbose_name="Logo Desa",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_profile/header/",
                        verbose_name="Gambar Header",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
            ],
            options={
                "verbose_name": "Profil Desa",
                "verbose_name_plural": "Profil Desa",
            },
        ),
        migrations.CreateModel(
            name="VillageProfilePageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Profil Desa",
                        max_length=200,
                        verbose_name="Judul Halaman",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Mengenal lebih dekat sejarah, budaya, dan kehidupan masyarakat desa kami.",
                        verbose_name="Deskripsi Halaman",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_profile/page_headers/",
                        verbose_name="Gambar Background",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Header Halaman Profil Desa",
                "verbose_name_plural": "Header Halaman Profil Desa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VillageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Ringkasan singkat sejarah (maksimal 500 karakter)",
                        max_length=500,
                        null=True,
                        verbose_name="Ringkasan",
                    ),
                ),
                ("content", models.TextField(verbose_name="Konten Lengkap")),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("FOUNDING", "Sejarah Berdiri"),
                            ("DEVELOPMENT", "Perkembangan"),
                            ("CULTURE", "Budaya & Tradisi"),
                            ("ECONOMY", "Ekonomi"),
                            ("SOCIAL", "Sosial"),
                            ("GOVERNMENT", "Pemerintahan"),
                            ("OTHER", "Lainnya"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Jenis Sejarah",
                    ),
                ),
                (
                    "period_start",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Periode Mulai",
                    ),
                ),
                (
                    "period_end",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Periode Berakhir",
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Tahun Mulai",
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Tahun Berakhir",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_history/featured/",
                        verbose_name="Gambar Utama",
                    ),
                ),
                (
                    "featured_image_caption",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Keterangan Gambar Utama",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Sumber informasi sejarah",
                        max_length=200,
                        null=True,
                        verbose_name="Sumber",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Penulis"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Dilihat"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
            ],
            options={
                "verbose_name": "Sejarah Desa",
                "verbose_name_plural": "Sejarah Desa",
                "ordering": ["-is_featured", "year_start", "period_start"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_featured"],
                        name="village_pro_is_acti_50e2f9_idx",
                    ),
                    models.Index(
                        fields=["history_type"], name="village_pro_history_b9cd3c_idx"
                    ),
                    models.Index(
                        fields=["year_start"], name="village_pro_year_st_910a25_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VillageOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("KEPALA_DESA", "Kepala Desa"),
                            ("SEKRETARIS", "Sekretaris Desa"),
                            ("BENDAHARA", "Bendahara Desa"),
                            ("KAUR_PEMERINTAHAN", "Kaur Pemerintahan"),
                            ("KAUR_PEMBANGUNAN", "Kaur Pembangunan"),
                            ("KAUR_KESRA", "Kaur Kesejahteraan Rakyat"),
                            ("KAUR_UMUM", "Kaur Umum"),
                            ("KAUR_KEUANGAN", "Kaur Keuangan"),
                            ("KADUS", "Kepala Dusun"),
                            ("RT", "Ketua RT"),
                            ("RW", "Ketua RW"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jabatan",
                    ),
                ),
                (
                    "custom_position",
                    models.CharField(
                        blank=True,
                        help_text="Isi jika memilih 'Lainnya' pada jabatan",
                        max_length=100,
                        null=True,
                        verbose_name="Jabatan Khusus",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_officials/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Lahir"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pendidikan"
                    ),
                ),
                (
                    "experience",
                    models.TextField(blank=True, null=True, verbose_name="Pengalaman"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Alamat"),
                ),
                ("start_date", models.DateField(verbose_name="Tanggal Mulai Jabatan")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Berakhir Jabatan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officials",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perangkat Desa",
                "verbose_name_plural": "Perangkat Desa",
                "ordering": ["display_order", "position", "name"],
            },
        ),
        migrations.CreateModel(
            name="VillageMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_maps/",
                        verbose_name="Gambar Peta",
                    ),
                ),
                (
                    "map_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="village_maps/files/",
                        verbose_name="File Peta",
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Skala Peta"
                    ),
                ),
                (
                    "projection",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Proyeksi"
                    ),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sistem Koordinat",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Sumber"
                    ),
                ),
                (
                    "year_created",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tahun Pembuatan"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peta Desa",
                "verbose_name_plural": "Peta Desa",
            },
        ),
        migrations.CreateModel(
            name="VillageGeography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Lintang"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, max_digits=10, verbose_name="Bujur"
                    ),
                ),
                ("altitude", models.IntegerField(verbose_name="Ketinggian (mdpl)")),
                ("climate", models.CharField(max_length=100, verbose_name="Iklim")),
                (
                    "rainfall",
                    models.IntegerField(verbose_name="Curah Hujan (mm/tahun)"),
                ),
                (
                    "temperature_min",
                    models.IntegerField(verbose_name="Suhu Minimum (°C)"),
                ),
                (
                    "temperature_max",
                    models.IntegerField(verbose_name="Suhu Maksimum (°C)"),
                ),
                (
                    "topography",
                    models.CharField(max_length=100, verbose_name="Topografi"),
                ),
                (
                    "soil_type",
                    models.CharField(max_length=100, verbose_name="Jenis Tanah"),
                ),
                (
                    "boundary_north",
                    models.CharField(max_length=100, verbose_name="Batas Utara"),
                ),
                (
                    "boundary_south",
                    models.CharField(max_length=100, verbose_name="Batas Selatan"),
                ),
                (
                    "boundary_east",
                    models.CharField(max_length=100, verbose_name="Batas Timur"),
                ),
                (
                    "boundary_west",
                    models.CharField(max_length=100, verbose_name="Batas Barat"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geography",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geografi Desa",
                "verbose_name_plural": "Geografi Desa",
            },
        ),
        migrations.CreateModel(
            name="VillageFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Fasilitas"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PENDIDIKAN", "Pendidikan"),
                            ("KESEHATAN", "Kesehatan"),
                            ("IBADAH", "Ibadah"),
                            ("OLAHRAGA", "Olahraga"),
                            ("UMUM", "Umum"),
                            ("PEMERINTAHAN", "Pemerintahan"),
                            ("EKONOMI", "Ekonomi"),
                            ("TRANSPORTASI", "Transportasi"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Fasilitas",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("BAIK", "Baik"),
                            ("CUKUP", "Cukup"),
                            ("RUSAK", "Rusak"),
                            ("RENOVASI", "Dalam Renovasi"),
                        ],
                        default="BAIK",
                        max_length=10,
                        verbose_name="Kondisi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("location", models.CharField(max_length=200, verbose_name="Lokasi")),
                (
                    "capacity",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kapasitas"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_facilities/",
                        verbose_name="Gambar",
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pengelola"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Penanggung Jawab",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telepon Kontak",
                    ),
                ),
                (
                    "operational_hours",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Jam Operasional",
                    ),
                ),
                (
                    "built_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tahun Dibangun"
                    ),
                ),
                (
                    "last_renovation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Renovasi Terakhir"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Fasilitas Umum"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fasilitas Desa",
                "verbose_name_plural": "Fasilitas Desa",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="VillageHistoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="village_history/photos/", verbose_name="Foto"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Keterangan"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "photographer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fotografer"
                    ),
                ),
                (
                    "photo_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Foto"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Lokasi"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Foto Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="village_profile.villagehistory",
                        verbose_name="Sejarah",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto Sejarah",
                "verbose_name_plural": "Foto Sejarah",
                "ordering": ["display_order", "-is_featured", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["history", "is_active"],
                        name="village_pro_history_b77d69_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="village_pro_is_feat_c8a683_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VillagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul Foto")),
                (
                    "image",
                    models.ImageField(upload_to="village_photos/", verbose_name="Foto"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("LANDSCAPE", "Pemandangan"),
                            ("BUILDING", "Bangunan"),
                            ("ACTIVITY", "Kegiatan"),
                            ("CULTURE", "Budaya"),
                            ("FACILITY", "Fasilitas"),
                            ("EVENT", "Acara"),
                            ("PEOPLE", "Masyarakat"),
                            ("NATURE", "Alam"),
                            ("OTHER", "Lainnya"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Jenis Foto",
                    ),
                ),
                (
                    "photographer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fotografer"
                    ),
                ),
                (
                    "photo_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Foto"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Lokasi"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Foto Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Dilihat"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto Desa",
                "verbose_name_plural": "Foto Desa",
                "ordering": ["-is_featured", "display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["village", "is_active"],
                        name="village_pro_village_e03888_idx",
                    ),
                    models.Index(
                        fields=["is_featured"], name="village_pro_is_feat_0f0799_idx"
                    ),
                    models.Index(
                        fields=["photo_type"], name="village_pro_photo_t_638e9e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VillageDemography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_population",
                    models.PositiveIntegerField(verbose_name="Total Penduduk"),
                ),
                (
                    "male_population",
                    models.PositiveIntegerField(verbose_name="Penduduk Laki-laki"),
                ),
                (
                    "female_population",
                    models.PositiveIntegerField(verbose_name="Penduduk Perempuan"),
                ),
                (
                    "total_families",
                    models.PositiveIntegerField(verbose_name="Jumlah Keluarga"),
                ),
                (
                    "population_density",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Kepadatan Penduduk (jiwa/km²)",
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Tingkat Pertumbuhan (%)",
                    ),
                ),
                (
                    "age_0_14",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usia 0-14 tahun"
                    ),
                ),
                (
                    "age_15_64",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usia 15-64 tahun"
                    ),
                ),
                (
                    "age_65_plus",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usia 65+ tahun"
                    ),
                ),
                (
                    "education_none",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tidak Sekolah"
                    ),
                ),
                (
                    "education_elementary",
                    models.PositiveIntegerField(default=0, verbose_name="SD"),
                ),
                (
                    "education_junior",
                    models.PositiveIntegerField(default=0, verbose_name="SMP"),
                ),
                (
                    "education_senior",
                    models.PositiveIntegerField(default=0, verbose_name="SMA"),
                ),
                (
                    "education_higher",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Perguruan Tinggi"
                    ),
                ),
                (
                    "employed",
                    models.PositiveIntegerField(default=0, verbose_name="Bekerja"),
                ),
                (
                    "unemployed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tidak Bekerja"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Tahun Data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demography",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demografi Desa",
                "verbose_name_plural": "Demografi Desa",
                "unique_together": {("village", "year")},
            },
        ),
        migrations.CreateModel(
            name="VillageStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_dusun",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah Dusun"),
                ),
                (
                    "total_rt",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah RT"),
                ),
                (
                    "total_rw",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah RW"),
                ),
                (
                    "total_facilities",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Fasilitas"
                    ),
                ),
                (
                    "total_umkm",
                    models.PositiveIntegerField(default=0, verbose_name="Total UMKM"),
                ),
                (
                    "poverty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tingkat Kemiskinan (%)",
                    ),
                ),
                (
                    "unemployment_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tingkat Pengangguran (%)",
                    ),
                ),
                (
                    "road_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Panjang Jalan (km)",
                    ),
                ),
                (
                    "electricity_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Cakupan Listrik (%)",
                    ),
                ),
                (
                    "water_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Cakupan Air Bersih (%)",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Tahun Data")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="village_profile.villageprofile",
                        verbose_name="Desa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistik Desa",
                "verbose_name_plural": "Statistik Desa",
                "ordering": ["-year"],
                "unique_together": {("village", "year")},
            },
        ),
    ]
