# Generated by Django 4.2.7 on 2025-09-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="villageprofile",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Luas Wilayah (km²)",
            ),
        ),
        migrations.AlterField(
            model_name="villageprofile",
            name="established_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tanggal Berdiri"
            ),
        ),
    ]
