# Generated by Django 4.2.7 on 2025-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0002_alter_villageprofile_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="villagephoto",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Tag"
            ),
        ),
    ]
