# Generated by Django 4.2.7 on 2025-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0004_villageofficial_penduduk"),
    ]

    operations = [
        migrations.AddField(
            model_name="villageofficial",
            name="birth_place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tempat Lahir"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="dusun",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dusun"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="gender",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="Jenis Kelamin"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nomor Rumah"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="lorong",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lorong"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="marital_status",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Status Perkawinan"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Handphone"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="nik",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="NIK"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pekerjaan"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Kode Pos"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="religion",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Agama"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="rt_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Nomor RT"
            ),
        ),
        migrations.AddField(
            model_name="villageofficial",
            name="rw_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Nomor RW"
            ),
        ),
    ]
