# Generated by Django 4.2.7 on 2025-09-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "village_profile",
            "0005_villageofficial_birth_place_villageofficial_dusun_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villageprofile",
            name="village_head",
        ),
    ]
