# Generated by Django 4.2.7 on 2025-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0006_remove_village_head_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="villageofficial",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Jenis Kelamin"
            ),
        ),
    ]
