# Generated by Django 4.2.7 on 2025-10-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0007_fix_gender_field_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villageprofile",
            name="header_image",
        ),
    ]
