# Generated by Django 4.2.7 on 2025-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0008_remove_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="villageprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="village_profile/profile/",
                verbose_name="Gambar Profil Desa",
            ),
        ),
    ]
