# Generated by Django 4.2.16 on 2025-10-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0009_add_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penduduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nik", models.CharField(max_length=16, unique=True)),
                ("alamat", models.TextField(blank=True)),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Penduduk",
            },
        ),
        migrations.RemoveField(
            model_name="villageofficial",
            name="penduduk",
        ),
    ]
