# Generated by Django 5.2.6 on 2025-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="penduduk",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="penduduk_photos/", verbose_name="Foto"
            ),
        ),
    ]
