# Generated by Django 4.2.7 on 2025-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0002_penduduk_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penduduk",
            name="relationship_to_head",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KEPALA_KELUARGA", "Kepala Keluarga"),
                    ("ISTRI", "Istri"),
                    ("ANAK", "Anak"),
                    ("MENANTU", "Menantu"),
                    ("CUCU", "Cucu"),
                    ("ORANG_TUA", "Orang Tua"),
                    ("MERTUA", "Mertua"),
                    ("FAMILI_LAIN", "Famili Lain"),
                    ("PEMBANTU", "Pembantu"),
                    ("LAINNYA", "Lainnya"),
                ],
                max_length=50,
                null=True,
                verbose_name="Hubungan dengan Kepala Keluarga",
            ),
        ),
    ]
