# Generated by Django 4.2.7 on 2025-09-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0003_add_relationship_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="lorong",
            name="population_count",
            field=models.IntegerField(
                default=0, help_text="Auto-calculated from residents"
            ),
        ),
        migrations.AlterField(
            model_name="dusun",
            name="population_count",
            field=models.IntegerField(
                default=0, help_text="Auto-calculated from residents"
            ),
        ),
        migrations.AlterField(
            model_name="lorong",
            name="house_count",
            field=models.IntegerField(
                default=0, help_text="Auto-calculated from residents"
            ),
        ),
    ]
