# Generated by Django 4.2.7 on 2025-09-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0004_lorong_population_count_alter_dusun_population_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dusun",
            name="kepala_dusun",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dusun_led",
                to="references.penduduk",
                verbose_name="Kepala Dusun",
            ),
        ),
        migrations.AddField(
            model_name="lorong",
            name="rt_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Nomor RT"
            ),
        ),
    ]
