# Generated by Django 4.2.7 on 2025-09-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0005_dusun_kepala_dusun_lorong_rt_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="RW",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rw_number", models.CharField(max_length=3, verbose_name="Nomor RW")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "population_count",
                    models.IntegerField(
                        default=0, help_text="Auto-calculated from residents"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dusun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rws",
                        to="references.dusun",
                    ),
                ),
                (
                    "ketua_rw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rw_led",
                        to="references.penduduk",
                        verbose_name="Ketua RW",
                    ),
                ),
            ],
            options={
                "verbose_name": "RW",
                "verbose_name_plural": "RW",
                "unique_together": {("dusun", "rw_number")},
            },
        ),
        migrations.CreateModel(
            name="RT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rt_number", models.CharField(max_length=3, verbose_name="Nomor RT")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "population_count",
                    models.IntegerField(
                        default=0, help_text="Auto-calculated from residents"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ketua_rt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rt_led",
                        to="references.penduduk",
                        verbose_name="Ketua RT",
                    ),
                ),
                (
                    "rw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rts",
                        to="references.rw",
                    ),
                ),
            ],
            options={
                "verbose_name": "RT",
                "verbose_name_plural": "RT",
                "unique_together": {("rw", "rt_number")},
            },
        ),
        migrations.AddField(
            model_name="penduduk",
            name="rt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="references.rt",
                verbose_name="RT",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="rw",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="references.rw",
                verbose_name="RW",
            ),
        ),
    ]
