# Generated by Django 4.2.7 on 2025-09-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0006_rw_rt_penduduk_rt_penduduk_rw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelajar",
            name="tahun_masuk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
